Repository pylint-dev/astroid, pull requests merged in 2021-05, with the labels that each got.

#972 Move a function in order to remove a circular import
  astroid/bases.py
  astroid/builder.py
  astroid/inference.py
Labels: enhancement

#927 Fix strong references to mutable objects in context.clone
  ChangeLog
  astroid/context.py
  tests/unittest_brain_numpy_core_umath.py
  tests/unittest_inference.py
  tests/unittest_regrtest.py
Labels: reviewed-waiting-updates

#933 Fix inference of instance attributes defined in base class
  ChangeLog
  astroid/bases.py
  tests/unittest_inference.py
Labels: reviewed-waiting-updates

#943 Add kind field to Const nodes
  ChangeLog
  astroid/node_classes.py
  astroid/rebuilder.py
  tests/unittest_nodes.py
Labels: reviewed-waiting-updates

#941 Inferring property fields in a class context when metaclass is present
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  astroid/scoped_nodes.py
  tests/unittest_scoped_nodes.py
Labels: reviewed-waiting-updates

#934 Fix inference cycle in getattr when a base is an astroid.Attribute
  ChangeLog
  astroid/inference.py
  tests/unittest_inference.py
Labels: pylint-tested, reviewed-waiting-updates

#983 Infer return value of None for correctly inferred functions with no returns
  ChangeLog
  astroid/bases.py
  astroid/scoped_nodes.py
  tests/unittest_inference.py
  tests/unittest_scoped_nodes.py
Labels: pylint-tested, reviewed-waiting-updates

#984 Fix 930 pyreverse regression
  ChangeLog
  astroid/interpreter/_import/spec.py
  astroid/manager.py
  astroid/modutils.py
  tests/unittest_modutils.py
Labels: pylint-tested, reviewed-waiting-updates

#986 Add initial support for pattern matching py310
  ChangeLog
  astroid/node_classes.py
  astroid/nodes.py
  astroid/rebuilder.py
  doc/api/astroid.nodes.rst
  setup.cfg
  tests/unittest_nodes.py
Labels: enhancement, python 3.10

#1002 Prepare for 2.5.7
  .copyrite_aliases
  ChangeLog
  astroid/as_string.py
  astroid/bases.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_numpy_core_function_base.py
  astroid/brain/brain_numpy_core_multiarray.py
  astroid/brain/brain_numpy_core_numeric.py
  astroid/brain/brain_six.py
  astroid/brain/brain_typing.py
  astroid/builder.py
  astroid/context.py
  astroid/exceptions.py
  astroid/inference.py
  astroid/interpreter/_import/spec.py
  astroid/manager.py
  astroid/mixins.py
  astroid/modutils.py
  astroid/node_classes.py
  astroid/nodes.py
  astroid/rebuilder.py
  astroid/scoped_nodes.py
  doc/release.md
  tests/unittest_brain.py
  tests/unittest_brain_numpy_core_umath.py
  tests/unittest_builder.py
  tests/unittest_inference.py
  tests/unittest_modutils.py
  tests/unittest_nodes.py
  tests/unittest_object_model.py
  tests/unittest_regrtest.py
  tests/unittest_scoped_nodes.py
Labels: task
