Repository pylint-dev/astroid, pull requests merged in 2021-07, with the labels that each got.

#1091 Handle the case where node is a Module in ``brain_builtin_inference``
  ChangeLog
  astroid/brain/brain_builtin_inference.py
Labels: crash, pylint-tested

#1093 Fix issues when inferring match variables
  ChangeLog
  astroid/builder.py
  astroid/node_classes.py
  astroid/protocols.py
  astroid/rebuilder.py
  tests/unittest_protocols.py
Labels: bug, python 3.10

#1092 Fix yield inference on inherited classes.
  ChangeLog
  astroid/bases.py
  astroid/protocols.py
  astroid/scoped_nodes.py
  tests/unittest_inference.py
Labels: bug, pylint-tested

#1099 Add new If guard helper methods
  ChangeLog
  astroid/node_classes.py
  tests/unittest_nodes.py
Labels: enhancement

#1101 Make TypedDict instance callable
  ChangeLog
  astroid/brain/brain_typing.py
  tests/unittest_brain.py
Labels: bug, pylint-tested

#1100 Guard against missing setuptools
  ChangeLog
  astroid/interpreter/_import/util.py
  setup.cfg
Labels: crash

#1102 Support lookup in nested non-FunctionDef scopes
  ChangeLog
  astroid/scoped_nodes.py
  tests/unittest_lookup.py
Labels: bug, pylint-tested

#1104 Catch StopIteration and reraise cleanly to fix pylint #4723
  astroid/protocols.py
Labels: crash

#1105 Remove redundant isinstance calls in brain_typing
  astroid/brain/brain_typing.py
Labels: pylint-tested

#1110 Fix wrong exception raised in infer_import_from
  ChangeLog
  astroid/inference.py
  tests/unittest_inference.py
Labels: crash

#1076 Infer the type of the result of calling typing.cast()
  ChangeLog
  astroid/brain/brain_typing.py
  tests/unittest_brain.py
Labels: brain, enhancement, pylint-tested
