Repository pylint-dev/astroid, pull requests merged in 2021-12, with the labels that each got.

#1283 Fix typing of ``Arguments.args``
  ChangeLog
  astroid/nodes/node_classes.py
Labels: task, documentation

#1285 Fix crash if a variable named "type" is subscripted in a generator expression
  ChangeLog
  astroid/brain/brain_type.py
  tests/unittest_inference.py
Labels: crash

#1249 Add parameter typing to ``assigned_stmts``
  astroid/nodes/node_classes.py
  astroid/protocols.py
Labels: task

#1289 Remove unused code - TreeRebuilder docstring
  astroid/rebuilder.py
Labels: maintenance

#1290 Add mypy ignores and docstrings to ``modutils`` and ``util.py``
  astroid/interpreter/_import/util.py
  astroid/modutils.py
Labels: task

#1253 Resolve symlinks in the import path
  ChangeLog
  astroid/modutils.py
Labels: bug

#1293 Add typing to ``brain_typing``
  astroid/brain/brain_typing.py
Labels: task

#1291 Add typing to ``_normalize_path`` and ``_cache_normalize_path``
  astroid/modutils.py
Labels: task

#1207 Prefer using the module loader to get source in builder.
  ChangeLog
  astroid/builder.py
Labels: enhancement, pylint-tested

#1295 Fix incorrect typing of optional default values
  astroid/brain/brain_re.py
  astroid/builder.py
  astroid/manager.py
  astroid/raw_building.py
Labels: task

#1297 Upgrade pylint to 2.12.2
  .github/workflows/ci.yaml
  astroid/interpreter/_import/spec.py
  astroid/manager.py
  astroid/nodes/node_ng.py
  requirements_test_pre_commit.txt
Labels: maintenance

#1294 Add stubs for ``setuptools`` and ``typed-ast`` to dependencies
  requirements_test.txt
Labels: task

#1299 Revert "Add stubs for ``setuptools`` and ``typed-ast`` to dependencies"
  requirements_test.txt
Labels: task

#1262 Make ``Module`` call the ``__init__`` of ``NodeNG``
  ChangeLog
  astroid/nodes/scoped_nodes.py
  tests/unittest_nodes_lineno.py
Labels: bug, enhancement, pylint-tested

#1296 Add typing to ``_ast``
  astroid/_ast.py
Labels: task

#1300 Upgrade mypy to 0.920
  .pre-commit-config.yaml
  requirements_test_pre_commit.txt
Labels: maintenance

#1302 Create ``scoped_nodes`` module
  astroid/nodes/scoped_nodes/__init__.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_scoped_nodes.py
Labels: task

#1304 Remove NoReturn
  astroid/nodes/node_ng.py
Labels: maintenance

#1303 Move ``_filter_stmts`` into its own file
  astroid/filter_statements.py
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: maintenance

#1308 Fix node.statement overload typing
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: maintenance

#1310 Upgrade mypy to 0.930
  .pre-commit-config.yaml
  requirements_test_pre_commit.txt
Labels: maintenance

#1298 Fix dataclass inference for marshmallow_dataclass
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: bug, needs review

#1307 Revert "Remove useless NoReturn in NodeNG.statement's typing (#1304)"
  astroid/nodes/node_ng.py
Labels: maintenance

#1314 Bump CI cache version
  .github/workflows/ci.yaml
Labels: task

#1318 Fix spelling
  astroid/nodes/node_classes.py
Labels: task

#1317 Fix node.statement overload typing - default argument
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: task

#1263 Fix frame() error on inferred node
  ChangeLog
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_nodes.py
Labels: bug

#1319 Revert "Revert "Remove useless NoReturn in NodeNG.statement's typing (#1304)""
  astroid/nodes/node_ng.py
Labels: maintenance

#1305 Add future=True to frame calls
  astroid/arguments.py
  astroid/bases.py
  astroid/builder.py
  astroid/helpers.py
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/protocols.py
  tests/unittest_builder.py
  tests/unittest_inference.py
  tests/unittest_manager.py
  tests/unittest_nodes.py
  tests/unittest_scoped_nodes.py
Labels: enhancement

#1292 Add typing to ``brain_dataclasses``
  astroid/brain/brain_dataclasses.py
Labels: task

#1321 Fix ``distutils`` path patching for setuptools >= 60.0.0
  ChangeLog
  astroid/interpreter/_import/spec.py
  tests/unittest_modutils.py
Labels: bug
