Repository pylint-dev/astroid, pull requests merged in 2021-10, with the labels that each got.

#1183 Bug pylint 4326
  ChangeLog
  astroid/brain/brain_numpy_core_numerictypes.py
  astroid/brain/brain_numpy_ndarray.py
  astroid/brain/brain_numpy_utils.py
  tests/unittest_brain_numpy_core_numerictypes.py
  tests/unittest_brain_numpy_ndarray.py
Labels: brain, pylint-tested

#1186 Fix ``relative-beyond-top-level`` false positive
  ChangeLog
  astroid/nodes/scoped_nodes.py
  tests/testdata/python3/data/beyond_top_level/import_package.py
  tests/testdata/python3/data/beyond_top_level/namespace_package/lower_level/helper_function.py
  tests/testdata/python3/data/beyond_top_level/namespace_package/plugin_api.py
  tests/testdata/python3/data/beyond_top_level/namespace_package/top_level_function.py
  tests/unittest_inference.py
Labels: bug

#1202 Deprecate ``is_typing_guard`` and ``is_sys_guard``
  ChangeLog
  astroid/nodes/node_classes.py
Labels: internal, deprecation

#1204 Fix regression introduced by #1186 and add tests
  astroid/nodes/scoped_nodes.py
  tests/testdata/python3/data/beyond_top_level_two/__init__.py
  tests/testdata/python3/data/beyond_top_level_two/a.py
  tests/testdata/python3/data/beyond_top_level_two/level1/__init__.py
  tests/testdata/python3/data/beyond_top_level_two/level1/beyond_top_level_two.py
  tests/unittest_inference.py
Labels: regression, pylint-tested
