Repository pylint-dev/astroid, pull requests merged in 2021-11, with the labels that each got.

#1232 Small changes
  ChangeLog
  astroid/decorators.py
  astroid/nodes/node_classes.py
  tests/unittest_inference.py
Labels: internal

#1217 Add typing to ``NodeNG.statement``
  astroid/exceptions.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes.py
  tests/unittest_builder.py
  tests/unittest_nodes.py
  tests/unittest_scoped_nodes.py
Labels: pylint-tested, internal

#1234 Fix crash on inference of ``__len__``
  ChangeLog
  astroid/helpers.py
  tests/unittest_brain.py
Labels: needs review, crash

#1233 Improve filtering of ``NamedExpr``, particularly within ``If`` nodes
  ChangeLog
  astroid/nodes/node_classes.py
  tests/unittest_regrtest.py
Labels: topic-control-flow, crash, python 3.8

#1238 More permissive version for typed-ast
  ChangeLog
  setup.cfg
Labels: bug, task

#1245 Fix ``mypy`` warnings for ``astroid/nodes/node_ng``
  astroid/nodes/node_ng.py
Labels: task

#1246 Fix `mypy` warnings for `astroid/builder` and `astroid/nodes/as_string`
  astroid/builder.py
  astroid/manager.py
  astroid/nodes/as_string.py
Labels: task

#1248 Add additional flags to ``mypy`` config and update ``type: ignore``'s
  astroid/nodes/node_ng.py
  astroid/rebuilder.py
  setup.cfg
  tests/unittest_protocols.py
  tests/unittest_regrtest.py
Labels: task

#1247 Add ``type: ignore`` to method reassignments
  astroid/inference.py
Labels: task

#1251 Add ``DeprecationWarning`` contextmanager to tests of deprecated methods
  tests/unittest_nodes.py
Labels: task

#1252 Change ``NoReturn`` to be encapsulated in strings
  ChangeLog
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes.py
Labels: bug

#1255 Remove forgotten debug ``print`` statement from tests
  tests/unittest_inference.py
Labels: task

#1257 Add ``InferenceContext`` to ``ClassModel``
  ChangeLog
  astroid/interpreter/objectmodel.py
  tests/unittest_regrtest.py
Labels: crash

#1261 Add annotations for always None attributes
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes.py
Labels: task

#1266 Always treat __class_getitem__ as a classmethod
  ChangeLog
  astroid/nodes/scoped_nodes.py
  tests/unittest_inference.py
Labels: bug, pylint-tested

#1270 Resolve dependency conflicts with pylint
  .github/workflows/ci.yaml
  requirements_test_min.txt
Labels: task

#1240 Add flake8 typing import to the pre-commit configuration
  .pre-commit-config.yaml
  requirements_test_pre_commit.txt
  setup.cfg
Labels: internal

#1269 Require Python 3.6.2
  ChangeLog
  setup.cfg
Labels: task

#1272 fix deque.insert() signature
  ChangeLog
  astroid/brain/brain_collections.py
Labels: bug, brain

#1235 Add ``future`` argument to all ``NodeNG.statement()`` calls
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/mixins.py
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes.py
  astroid/protocols.py
  tests/unittest_builder.py
Labels: internal

#1244 Fix ``mypy`` warnings for ``astroid/rebuilder``
  astroid/nodes/node_classes.py
  astroid/rebuilder.py
Labels: task, pylint-tested

#1275 Change order of decorators in tests
  tests/unittest_scoped_nodes.py
Labels: task

#1277 Upgrade to pylint 2.12 and enable ``for_any_all`` checker
  astroid/brain/brain_numpy_utils.py
  astroid/modutils.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes.py
  pylintrc
  requirements_test_pre_commit.txt
  tests/unittest_brain.py
  tests/unittest_inference.py
  tests/unittest_nodes.py
Labels: internal

#1278 Update pylintrc
  pylintrc
Labels: internal
