Repository pylint-dev/astroid, pull requests merged in 2021-08, with the labels that each got.

#1089 Don't calculate slots when MRO parsing fails.
  ChangeLog
  astroid/scoped_nodes.py
  tests/unittest_scoped_nodes.py
Labels: bug, pylint-tested

#1097 Fix incorrect scope for functools partials
  astroid/brain/brain_functools.py
  astroid/node_classes.py
  astroid/objects.py
  tests/unittest_brain.py
Labels: bug, pylint-tested

#1114 Update pylint to 2.9.6
  astroid/node_classes.py
  astroid/protocols.py
  astroid/rebuilder.py
  requirements_test_pre_commit.txt
  script/bump_changelog.py
  tests/unittest_manager.py
  tests/unittest_modutils.py
  tests/unittest_nodes.py
Labels: internal

#935 Conditional test pickle
  tests/testdata/python3/data/conditional.py
  tests/testdata/python3/data/conditional_import/__init__.py
  tests/unittest_nodes.py
Labels: enhancement, needs review

#1119 Readme fixes
  README.rst
Labels: documentation, internal

#1118 Remove use of deprecated ``node_classes`` and ``scoped_node`` API in astroid
  astroid/__init__.py
  astroid/as_string.py
  astroid/bases.py
  astroid/brain/brain_attrs.py
  astroid/brain/brain_boto3.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_collections.py
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_fstrings.py
  astroid/brain/brain_functools.py
  astroid/brain/brain_hypothesis.py
  astroid/brain/brain_multiprocessing.py
  astroid/brain/brain_numpy_core_function_base.py
  astroid/brain/brain_numpy_core_multiarray.py
  astroid/brain/brain_numpy_core_numeric.py
  astroid/brain/brain_numpy_ndarray.py
  astroid/brain/brain_numpy_utils.py
  astroid/brain/brain_random.py
  astroid/brain/brain_type.py
  astroid/brain/brain_typing.py
  astroid/brain/brain_uuid.py
  astroid/brain/helpers.py
  astroid/builder.py
  astroid/context.py
  astroid/helpers.py
  astroid/inference.py
  astroid/interpreter/objectmodel.py
  astroid/nodes.py
  astroid/nodes/__init__.py
  astroid/objects.py
  astroid/protocols.py
  astroid/raw_building.py
  doc/api/base_nodes.rst
  tests/testdata/python3/data/module.py
  tests/unittest_lookup.py
  tests/unittest_modutils.py
  tests/unittest_nodes.py
  tests/unittest_protocols.py
  tests/unittest_python3.py
  tests/unittest_scoped_nodes.py
  tests/unittest_utils.py
Labels: task, pylint-tested, internal

#1127 Bug pylint 4060
  ChangeLog
  astroid/brain/brain_unittest.py
  astroid/interpreter/_import/spec.py
  astroid/manager.py
  tests/unittest_brain_unittest.py
Labels: enhancement, brain

#1128 Add pylintrc config for typing extension
  pylintrc
Labels: task

#1126 Add inference tips for dataclass attributes
  ChangeLog
  astroid/brain/brain_dataclasses.py
  astroid/nodes/node_classes.py
  astroid/transforms.py
  tests/unittest_brain.py
  tests/unittest_brain_dataclasses.py
Labels: bug, enhancement

#1131 Fixed import of LookupMixIn from astroid.node_classes
  ChangeLog
  astroid/node_classes.py
Labels: regression

#1135 Fix variable collision in _infer_stmts
  astroid/bases.py
Labels: pylint-tested, internal

#1140 Generate synthetic __init__ method for dataclasses
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: enhancement

#1154 Bug pylint 4896
  ChangeLog
  astroid/brain/brain_ctypes.py
  tests/unittest_brain_ctypes.py
Labels: pylint-tested

#1148 Bug pylint 3342
  ChangeLog
  astroid/builder.py
  astroid/manager.py
  astroid/modutils.py
  astroid/raw_building.py
  astroid/test_utils.py
  tests/unittest_modutils.py
Labels: bug, brain, pylint-tested
