Repository pylint-dev/astroid, pull requests merged in 2021-04, with the labels that each got.

#921 Bug pylint 4206
  ChangeLog
  astroid/brain/brain_collections.py
  astroid/brain/brain_typing.py
  astroid/scoped_nodes.py
  tests/unittest_brain.py
Labels: enhancement, high-effort

#928 Use inference_tip for typing.TypedDict brain
  ChangeLog
  astroid/brain/brain_typing.py
  tests/unittest_brain.py
Labels: reviewed-waiting-updates

#948 Add inference tip for ``typing.Tuple``
  ChangeLog
  astroid/brain/brain_typing.py
  tests/unittest_brain.py
Labels: reviewed-waiting-updates

#956 Fix crash when evaluating ``typing.NamedTuple``
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  tests/unittest_brain.py
Labels: reviewed-waiting-updates

#961 Fix pre_commit requirements
  requirements_test_pre_commit.txt
Labels: task

#964 Add black-disable-checker
  .pre-commit-config.yaml
Labels: task

#963 Update packaging - use setup.cfg for metadata
  MANIFEST.in
  astroid/__pkginfo__.py
  pytest.ini
  setup.cfg
  setup.py
Labels: task

#970 Don't upload coverage from travis
  .travis.yml
Labels: task

#969 Add __init__ to astroid.brain package
  astroid/__init__.py
  astroid/brain/__init__.py
  astroid/brain/brain_numpy_core_function_base.py
  astroid/brain/brain_numpy_core_multiarray.py
  astroid/brain/brain_numpy_core_numeric.py
Labels: task

#976 Retrocompatibility with old version of pylint
  astroid/__init__.py
  astroid/__pkginfo__.py
Labels: bug, regression

#982 Add pre commit ci
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  README.rst
Labels: task
