Repository pylint-dev/astroid, pull requests merged in 2021-09, with the labels that each got.

#1157 Deprecate some default values for node init calls
  ChangeLog
  astroid/decorators.py
  astroid/nodes/node_classes.py
  astroid/raw_building.py
  setup.cfg
  tests/unittest_decorators.py
  tests/unittest_transforms.py
Labels: deprecation

#1160 Add ``astroid.objects.ExceptionInstance`` import
  astroid/__init__.py
Labels: internal

#1166 Recognize nested classes in classes inherited from NamedTuple
  astroid/brain/brain_namedtuple_enum.py
  tests/unittest_brain.py
Labels: bug

#1161 Support pyz imports
  ChangeLog
  astroid/manager.py
  tests/unittest_manager.py
Labels: enhancement

#1165 Fix crash on datafields
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: crash

#1168 Add typing to ``NodeNG.nodes_of_class``
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes.py
Labels: internal

#1169 Add node_ancestors method
  ChangeLog
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
Labels: internal

#1163 Add typing in tests directory
  tests/resources.py
  tests/unittest_brain.py
  tests/unittest_brain_ctypes.py
  tests/unittest_brain_dataclasses.py
  tests/unittest_builder.py
  tests/unittest_helpers.py
  tests/unittest_inference.py
  tests/unittest_inference_calls.py
  tests/unittest_lookup.py
  tests/unittest_manager.py
  tests/unittest_modutils.py
  tests/unittest_nodes.py
  tests/unittest_object_model.py
  tests/unittest_objects.py
  tests/unittest_protocols.py
  tests/unittest_python3.py
  tests/unittest_raw_building.py
  tests/unittest_regrtest.py
  tests/unittest_scoped_nodes.py
  tests/unittest_transforms.py
  tests/unittest_utils.py
Labels: internal

#979 Add inference of Compare nodes
  astroid/inference.py
  tests/unittest_inference.py
Labels: enhancement

#1175 Fix documentation after changes to astroid.nodes
  ChangeLog
  doc/api/astroid.nodes.rst
  doc/api/base_nodes.rst
Labels: documentation

#1174 Add `Arguments` typing to `Lambda` & `FunctionDef`
  astroid/nodes/scoped_nodes.py
Labels: pylint-tested, internal

#1170 Add typing to `scope()`
  astroid/exceptions.py
  astroid/nodes/__init__.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes.py
  doc/api/astroid.exceptions.rst
  doc/api/base_nodes.rst
  tests/unittest_builder.py
  tests/unittest_lookup.py
  tests/unittest_nodes.py
  tests/unittest_scoped_nodes.py
Labels: internal

#1180 Add f-strings with `flynt`
  astroid/bases.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_gi.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_subprocess.py
  astroid/context.py
  astroid/decorators.py
  astroid/exceptions.py
  astroid/interpreter/_import/spec.py
  astroid/nodes/as_string.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  script/bump_changelog.py
  tests/unittest_brain.py
  tests/unittest_brain_numpy_core_fromnumeric.py
  tests/unittest_brain_numpy_core_function_base.py
  tests/unittest_brain_numpy_core_multiarray.py
  tests/unittest_brain_numpy_core_numeric.py
  tests/unittest_brain_numpy_core_umath.py
  tests/unittest_brain_numpy_ndarray.py
  tests/unittest_inference.py
  tests/unittest_regrtest.py
  tests/unittest_scoped_nodes.py
Labels: internal

#1178 Support dataclass inference for pydantic.dataclasses.
  ChangeLog
  astroid/brain/brain_dataclasses.py
Labels: bug

#1182 Small improvements to Compare infer
  astroid/inference.py
Labels: internal

#1185 Fix regression on Compare node inference
  ChangeLog
  astroid/inference.py
  tests/unittest_inference.py
Labels: crash, regression

#1176 Bug pylint 4960
  ChangeLog
  astroid/brain/brain_numpy_ma.py
  astroid/builder.py
  tests/unittest_brain_numpy_ma.py
Labels: bug, brain, pylint-tested

#1190 Remove deprecation warning raised by own astroid code
  ChangeLog
  astroid/__init__.py
Labels: pylint-tested, internal, deprecation

#1187 continuing #839: Extend attrs brain to support provisional APIs
  ChangeLog
  astroid/brain/brain_attrs.py
  tests/unittest_brain.py
Labels: brain

#1172 Feature / Bug Fix: Brain for the stdlib signal module
  astroid/brain/brain_signal.py
  tests/unittest_brain_signal.py
Labels: enhancement

#1192 Improve brain for typing.Callable + typing.Type
  ChangeLog
  astroid/brain/brain_typing.py
  tests/unittest_brain.py
Labels: brain
