Repository pylint-dev/astroid, pull requests merged in 2021-06, with the labels that each got.

#1010 Improve support for Pattern Matching
  ChangeLog
  astroid/as_string.py
  astroid/node_classes.py
  astroid/rebuilder.py
  tests/unittest_nodes.py
Labels: enhancement, python 3.10

#1011 Add lineno and col_offset for `Keyword` nodes
  ChangeLog
  astroid/rebuilder.py
Labels: enhancement, python 3.9

#1009 Performance improvements to counter context.clone slowdown
  ChangeLog
  astroid/context.py
  astroid/helpers.py
  astroid/node_classes.py
  astroid/transforms.py
Labels: pylint-tested

#1013 Prepare for 2.5.8 release
  ChangeLog
  astroid/as_string.py
  astroid/bases.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_six.py
  astroid/builder.py
  astroid/exceptions.py
  astroid/helpers.py
  astroid/inference.py
  astroid/interpreter/_import/spec.py
  astroid/manager.py
  astroid/mixins.py
  astroid/modutils.py
  astroid/node_classes.py
  astroid/nodes.py
  astroid/rebuilder.py
  astroid/transforms.py
  tests/unittest_brain_numpy_core_umath.py
  tests/unittest_builder.py
  tests/unittest_inference.py
  tests/unittest_modutils.py
  tests/unittest_nodes.py
  tests/unittest_object_model.py
  tests/unittest_regrtest.py
  tests/unittest_scoped_nodes.py
Labels: task

#1021 Add missing type annotations for Match nodes
  astroid/node_classes.py
Labels: python 3.10

#1022 Add exclude_lines coverage
  .coveragerc
Labels: task

#1023 Remove py2 nodes
  ChangeLog
  astroid/node_classes.py
  astroid/nodes.py
  astroid/rebuilder.py
  doc/api/astroid.nodes.rst
Labels: task

#1019 Rebuilder improvements and cleanup
  astroid/rebuilder.py
Labels: internal

#1024 Add type annotations to rebuilder
  astroid/rebuilder.py
Labels: internal

#1025 Deprecate Ellipsis node
  ChangeLog
  astroid/as_string.py
  astroid/node_classes.py
  astroid/rebuilder.py
  tests/unittest_nodes.py
Labels: enhancement, internal

#1020 Improve inference of Enum members called "name" and "value"
  ChangeLog
  astroid/bases.py
  astroid/brain/brain_namedtuple_enum.py
  tests/unittest_brain.py
Labels: brain, enhancement

#1026 Deprecate Index and ExtSlice nodes
  ChangeLog
  astroid/as_string.py
  astroid/node_classes.py
  astroid/rebuilder.py
Labels: enhancement, internal

#1028 Fix/pylint2036 enum py310
  ChangeLog
  astroid/bases.py
Labels: brain, enhancement

#1032 Small fix + improvements to Match nodes
  astroid/node_classes.py
  tests/unittest_nodes.py
Labels: internal

#1033 Update Match nodes to be internally consistent
  ChangeLog
  astroid/node_classes.py
  astroid/rebuilder.py
Labels: enhancement, internal

#1034 Create a file for inference tip
  astroid/__init__.py
  astroid/inference_tip.py
Labels: internal, pylint-tested, task

#1036 Remove unused rebuilder methods
  astroid/rebuilder.py
Labels: internal

#1038 Add MultiLineBlockMixin to MatchCase
  astroid/node_classes.py
Labels: enhancement, python 3.10

#1037 Add Pattern base class
  ChangeLog
  astroid/node_classes.py
  astroid/rebuilder.py
  doc/api/base_nodes.rst
Labels: enhancement, python 3.10

#1001 Improve Sphinx config
  doc/conf.py
  doc/requirements.txt
  tox.ini
Labels: documentation

#1041 Type annotations for nodes 02
  astroid/node_classes.py
Labels: internal

#1042 Type annotations for nodes 03
  astroid/node_classes.py
  astroid/rebuilder.py
Labels: internal, pylint-tested

#1044 Type annotations for nodes 04
  astroid/node_classes.py
  astroid/rebuilder.py
Labels: internal, pylint-tested

#1046 Type annotations for nodes 05
  astroid/node_classes.py
Labels: internal, pylint-tested

#1047 Type annotations for nodes 06
  astroid/node_classes.py
Labels: internal

#1048 Type annotations for nodes 07
  astroid/node_classes.py
Labels: internal, pylint-tested

#1051 Remove Optional annotation if parameter is required
  astroid/node_classes.py
Labels: internal

#1055 Typing 08
  astroid/node_classes.py
Labels: internal

#1056 Type annotations for nodes 09
  astroid/node_classes.py
Labels: internal, pylint-tested

#1061 Type annotations for nodes 10
  astroid/node_classes.py
Labels: internal, pylint-tested

#1063 Type annotations for nodes 11
  astroid/node_classes.py
Labels: internal

#1066 Small fixes following pep8 changes
  pylintrc
  tests/unittest_nodes.py
Labels: internal, minor, task

#1065 Remove default init values Arguments + fix raw_building
  astroid/node_classes.py
  astroid/raw_building.py
  tests/unittest_raw_building.py
Labels: internal, pylint-tested

#1068 Add mypy configuration
  .pre-commit-config.yaml
  requirements_test_pre_commit.txt
  setup.cfg
Labels: internal, task

#1062 Misc typing improvements
  astroid/rebuilder.py
Labels: internal, pylint-tested

#1071 Add code analysis provided by GitHub
  .github/workflows/codeql-analysis.yml
Labels: internal, task

#1074 Add dict as base for TypedDict
  ChangeLog
  astroid/brain/brain_typing.py
  tests/unittest_brain.py
Labels: bug, python 3.9

#1082 Handle inference fail when calculating lenght of a node
  ChangeLog
  astroid/helpers.py
Labels: blocker, crash, pylint-tested

#1081 Catch the StopIteration that result from PEP-479 or add default value in ``next``
  ChangeLog
  astroid/arguments.py
  astroid/bases.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_functools.py
  astroid/brain/brain_multiprocessing.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_nose.py
  astroid/brain/brain_six.py
  astroid/brain/brain_typing.py
  astroid/decorators.py
  astroid/helpers.py
  astroid/inference.py
  astroid/interpreter/objectmodel.py
  astroid/node_classes.py
  astroid/protocols.py
  astroid/scoped_nodes.py
Labels: blocker, crash, pylint-tested

#1083 Use explicit `__all__` for `astroid.nodes`
  astroid/nodes.py
Labels: task
