Repository pylint-dev/astroid, pull requests merged in 2022-01, with the labels that each got.

#1325 Fix import astroid.scoped_nodes
  astroid/nodes/scoped_nodes/__init__.py
Labels: proposal, discussion

#1333 Fix finding packages without an ``__init__.py``
  ChangeLog
  astroid/modutils.py
  tests/unittest_modutils.py
Labels: regression

#1345 Add typing to ``FunctionDef`` decorators attributes
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: maintenance

#1352 Use ``warnings.simplefilter`` instead of ``filterwarnings``
  astroid/raw_building.py
Labels: topic-performance, maintenance

#1353 Add typing to ``__str__``, ``__repr__`` and ``_repr_name``
  astroid/nodes/node_ng.py
Labels: maintenance

#1354 Add typing to ``LocalsDictNodeNG.locals``
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: maintenance

#1355 Rearrange and type attribute definition of ``nodes.Module``
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: maintenance

#1356 Fix typing in ``arguments.py``
  astroid/arguments.py
Labels: maintenance

#1357 Fix incorrect typing of ``doc`` attribute of ``Module``
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: maintenance

#1359 Use ``_extract_single_node`` in ``brain_re``
  astroid/brain/brain_re.py
Labels: maintenance

#1331 Add support for attrs v21.3.0+
  astroid/brain/brain_attrs.py
  tests/unittest_brain.py
Labels: enhancement, brain

#1366 Fix builtin inference on property not including function arguments
  ChangeLog
  astroid/brain/brain_builtin_inference.py
  tests/unittest_brain_builtin.py
Labels: bug

#1364 Add regression test for #1124
  astroid/const.py
  tests/unittest_scoped_nodes.py
Labels: regression

#1370 Fix crash on ``Super.getattr`` for previously uninferable attributes
  ChangeLog
  astroid/nodes/node_ng.py
  tests/resources.py
  tests/testdata/python3/data/max_inferable_limit_for_classes/main.py
  tests/testdata/python3/data/max_inferable_limit_for_classes/nodes/roles.py
  tests/testdata/python3/data/max_inferable_limit_for_classes/other_funcs.py
  tests/unittest_regrtest.py
Labels: crash

#1371 Add a changelog entry for attrs support
  ChangeLog
Labels: maintenance

#1376 Update mypy requirement to 0.931
  requirements_test_pre_commit.txt
Labels: task

#1322 Change site packages look up to use sysconfig instead of distutils
  astroid/modutils.py
Labels: maintenance

#1378 Add timeouts for CI jobs
  .github/workflows/ci.yaml
Labels: maintenance
