Repository pylint-dev/astroid, pull requests merged in 2022-08, with the labels that each got.

#1733 Set isolated build in tox.ini
  tox.ini
Labels: Maintenance

#1734 Fix false positive with inference of type-annotated Enum classes.
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  tests/unittest_scoped_nodes.py
Labels: Bug 🪳

#1714 Fix crash in `ExplicitNamespacePackageFinder`
  ChangeLog
  astroid/interpreter/_import/util.py
  requirements_test_brain.txt
  tests/unittest_modutils.py
Labels: Needs backport, pylint-tested, Crash 💥

#1739 Fix a crash inferring invalid string formatting with `%`
  ChangeLog
  astroid/inference.py
  tests/unittest_inference.py
Labels: Needs backport

#1743 Fix crash with inference of type-annotated Enum classes
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  tests/unittest_scoped_nodes.py
Labels: Needs backport, Crash 💥

#1746 Don't add ``KW_ONLY`` fields to dataclass fields
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: Bug 🪳, Needs backport

#1745 Bump ``wrapt`` to ``1.14``
  ChangeLog
  pyproject.toml
Labels: Needs backport, dependency

#1742 Fix false positive with inference of `http` module
  ChangeLog
  astroid/brain/brain_http.py
  tests/unittest_brain.py
Labels: Bug 🪳, Needs backport, Brain 🧠

#1749 Remove str instance in model of BaseException.attrs
  astroid/interpreter/objectmodel.py
  tests/unittest_object_model.py
Labels: Bug 🪳, Needs backport

#1747 Don't rely on the module cache when "importing self"
  ChangeLog
  astroid/manager.py
  astroid/nodes/_base_nodes.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/testdata/python3/data/import_conflicting_names/math.py
  tests/unittest_manager.py
Labels: Bug 🪳, pylint-tested

#1753 Fix crash involving non-standard type comments
  ChangeLog
  astroid/rebuilder.py
  tests/unittest_builder.py
Labels: Needs backport, Crash 💥

#1757 Fix namespace package detection for frozen stdlib modules on PyPy
  ChangeLog
  astroid/interpreter/_import/util.py
  tests/unittest_manager.py
Labels: Bug 🪳, Needs backport, PyPy

#1758 Add a comment about missing ``__spec__`` on ``PyPy``
  astroid/interpreter/_import/util.py
Labels: Needs backport, Maintenance

#1756 Prevent first-party imports from being resolved to `site-packages`
  ChangeLog
  astroid/interpreter/_import/util.py
  tests/unittest_manager.py
Labels: Bug 🪳, Needs backport, pylint-tested
