Repository pylint-dev/astroid, pull requests merged in 2022-11, with the labels that each got.

#1861 Prevent returning an empty list for ``ClassDef.slots()``
  ChangeLog
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_brain.py
Labels: Bug 🪳, Needs backport

#1860 CI improvements
  .github/workflows/ci.yaml
  .github/workflows/release-tests.yml
  .github/workflows/release.yml
Labels: Needs backport, Maintenance

#1862 Infer the `length` argument of the ``random.sample`` function.
  ChangeLog
  astroid/brain/brain_random.py
  tests/unittest_brain.py
Labels: Bug 🪳, Needs backport

#1863 Move changelog entries to 2.12.13
  ChangeLog
Labels: Needs backport

#1837 Add typing for `set_local`
  astroid/builder.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/mixin.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/nodes/scoped_nodes/utils.py
  astroid/raw_building.py
  astroid/rebuilder.py
Labels: Maintenance

#1866 Prevent a crash when inferring calls to `str.format` with invalid args
  ChangeLog
  astroid/brain/brain_builtin_inference.py
  tests/unittest_brain_builtin.py
Labels: Needs backport, Crash 💥

#1844 Fix uncaught ValueError on inference of __getitem__ with slice(..., ..., 0)
  ChangeLog
  astroid/inference.py
  astroid/nodes/node_classes.py
  tests/unittest_inference.py
Labels: Needs backport, Crash 💥

#1869 Use stable astroid for pylint CI check
  .github/workflows/ci.yaml
Labels: Maintenance

#1872 Update mypy to 0.991
  .pre-commit-config.yaml
  astroid/builder.py
  requirements_test_pre_commit.txt
Labels: dependency

#1873 Add boilerplate for documenting an upgrade guide
  doc/upgrade_guide.rst
  doc/whatsnew.rst
Labels: Documentation :green_book:

#1874 Move `_value2member_map_` changelog back to 2.12.11
  ChangeLog
Labels: Documentation :green_book:, Needs backport

#1878 Add some str annotations
  astroid/bases.py
  astroid/brain/brain_signal.py
  astroid/brain/brain_six.py
  astroid/context.py
  astroid/nodes/as_string.py
  astroid/nodes/scoped_nodes/mixin.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/objects.py
  astroid/protocols.py
  astroid/util.py
Labels: Maintenance

#1877 Add some bool annotations
  astroid/arguments.py
  astroid/bases.py
  astroid/brain/brain_argparse.py
  astroid/brain/brain_attrs.py
  astroid/brain/brain_boto3.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_functools.py
  astroid/brain/brain_gi.py
  astroid/brain/brain_hypothesis.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_numpy_ndarray.py
  astroid/brain/brain_random.py
  astroid/brain/brain_six.py
  astroid/brain/brain_type.py
  astroid/brain/brain_typing.py
  astroid/context.py
  astroid/filter_statements.py
  astroid/helpers.py
  astroid/inference.py
  astroid/interpreter/objectmodel.py
  astroid/nodes/as_string.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/mixin.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/raw_building.py
  astroid/util.py
Labels: Maintenance

#1883 Inference context annotations
  astroid/arguments.py
  astroid/bases.py
  astroid/brain/brain_argparse.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_collections.py
  astroid/brain/brain_functools.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_numpy_ndarray.py
  astroid/brain/brain_numpy_utils.py
  astroid/brain/brain_random.py
  astroid/brain/brain_type.py
  astroid/brain/brain_typing.py
  astroid/context.py
  astroid/decorators.py
  astroid/helpers.py
  astroid/inference.py
  astroid/interpreter/objectmodel.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/objects.py
Labels: Maintenance

#1884 Fix misc type issues
  astroid/inference.py
  astroid/interpreter/objectmodel.py
  astroid/nodes/scoped_nodes/mixin.py
  astroid/test_utils.py
Labels: Maintenance

#1885 Add some type annotations to raw_building
  astroid/const.py
  astroid/nodes/node_classes.py
  astroid/raw_building.py
Labels: Maintenance

#1787 Partial typing of the ``infer_binary_op`` path
  astroid/bases.py
  astroid/helpers.py
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/protocols.py
  astroid/typing.py
Labels: Maintenance

#1893 Use dict literals
  astroid/nodes/node_classes.py
  astroid/protocols.py
Labels: Maintenance

#1894 Finalize typing of the ``infer_binary_op`` path
  astroid/inference.py
Labels: Maintenance
