Repository pylint-dev/astroid, pull requests merged in 2022-04, with the labels that each got.

#1505 Fix instance_attrs building error in Qt brain
  .github/workflows/release-tests.yml
  ChangeLog
  astroid/brain/brain_qt.py
  astroid/nodes/scoped_nodes/mixin.py
  requirements_test_brain.txt
  tests/unittest_brain_qt.py
Labels: bug, needs-backport, brain

#1510 Reduce the number of CI runners
  .github/workflows/ci.yaml
Labels: maintenance

#1518 Fix a crash in the `gi` brain
  ChangeLog
  astroid/brain/brain_gi.py
Labels: needs-backport, brain, crash

#1517 Enable ``3.11`` in the CI
  .github/workflows/ci.yaml
  requirements_test_brain.txt
Labels: python 3.11

#1524 Remove unused ci settings
  .github/workflows/ci.yaml
Labels: maintenance

#1515 Fix ``re`` brain on ``3.11``
  ChangeLog
  astroid/brain/brain_re.py
  astroid/const.py
Labels: python 3.11

#1520 Fix ``col_offset`` attribute for nodes involving ``with`` on ``PyPy``
  ChangeLog
  astroid/rebuilder.py
  tests/unittest_nodes.py
Labels: bug, needs-backport

#1513 Find frozen stdlib modules
  ChangeLog
  astroid/interpreter/_import/spec.py
  astroid/manager.py
Labels: python 3.11, ast

#1525 Add annotations for `ModuleType`
  ChangeLog
  astroid/interpreter/_import/spec.py
  astroid/modutils.py
Labels: maintenance

#1526 Add annotations for `ParserModule`
  astroid/_ast.py
Labels: maintenance

#1527 Rename TypeVars
  astroid/decorators.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/rebuilder.py
Labels: maintenance

#1533 Install Qt on 3.10 Linux runner
  .github/workflows/ci.yaml
  .github/workflows/release-tests.yml
Labels: maintenance

#1534 Fix a crash when `_filter_stmts` encounters an `EmptyNode`
  ChangeLog
  astroid/filter_statements.py
  tests/unittest_filter_statements.py
Labels: bug, needs-backport, pylint-tested

#1531 Make `FunctionDef.implicit_parameters` return 1 for methods
  ChangeLog
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_brain_qt.py
  tests/unittest_scoped_nodes.py
Labels: bug, needs-backport, pylint-tested

#1535 Fix a crash involving two starred expressions inside a call
  ChangeLog
  astroid/protocols.py
  tests/unittest_protocols.py
Labels: bug, needs-backport, pylint-tested
