Repository pylint-dev/astroid, pull requests merged in 2022-09, with the labels that each got.

#1763 Fix a crash involving `Uninferable` args to `namedtuple`
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  tests/unittest_brain.py
Labels: Needs backport, pylint-tested, Crash 💥

#1764 Handle ``dataclass`` ``kw_only`` keyword correctly
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: Bug 🪳, Needs backport, python 3.10, pylint-tested

#1768 Fix crash in ``dataclass`` brain
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: Needs backport, Crash 💥

#1771 Parse default values in ``dataclass`` attributes correctly
  ChangeLog
  astroid/brain/brain_dataclasses.py
  astroid/nodes/node_classes.py
  tests/unittest_brain_dataclasses.py
Labels: Bug 🪳, Needs backport, Regression

#1770 Fix crash in ``dataclass`` brain
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: Needs backport, Crash 💥

#1773 Fix a crash on ``namedtuples`` that use ``typename``
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  tests/unittest_brain.py
Labels: Bug 🪳, Needs backport, Crash 💥

#1774 Fixed the ``__init__`` of ``dataclassess`` with multiple inheritance
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: Needs backport, Regression

#1783 Give a created Arguments node a parent
  astroid/interpreter/objectmodel.py
Labels: Maintenance

#1782 Create a ``CacheManager`` class to manage storing and clearing caches
  ChangeLog
  astroid/_cache.py
  astroid/decorators.py
  astroid/manager.py
Labels: Bug 🪳, Memory usage

#1678 Add typing to ``metaclass`` methods
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: Maintenance

#1777 Stop detecting modules compiled by `cffi` as namespace packages
  ChangeLog
  astroid/interpreter/_import/util.py
Labels: Needs backport, pylint-tested, Crash 💥

#1788 Fix typo
  ChangeLog
Labels: Maintenance

#1790 Don't set flake8 max-complexity and max-line-length and also ignore them
  setup.cfg
Labels: Maintenance

#1789 Migrate configs for isort, mypy, and pytest into pyproject.toml
  pyproject.toml
  setup.cfg
Labels: Maintenance

#1798 pylintrc: Remove duplicate plugin pylint.extensions.code_style
  pylintrc
Labels: Maintenance

#1804 Finish typing of ``AstroidManagerBrain``
  astroid/manager.py
  astroid/typing.py
Labels: Maintenance

#1806 Finish typing of ``astroid.manager.py``
  astroid/builder.py
  astroid/exceptions.py
  astroid/inference_tip.py
  astroid/manager.py
  astroid/raw_building.py
Labels: Maintenance

#1807 Finish typing of ``astroid.builder.py``
  astroid/builder.py
  astroid/exceptions.py
  astroid/raw_building.py
Labels: Maintenance

#1801 Handle empty ``modname`` in ``ast_from_module_name``
  astroid/manager.py
  tests/unittest_manager.py
Labels: Bug 🪳
