Repository pylint-dev/astroid, pull requests merged in 2022-03, with the labels that each got.

#1416 Clarify changelog entry
  ChangeLog
Labels: documentation

#1419 Create dependabot configuration
  .github/dependabot.yml
Labels: maintenance

#1411 Add tests for position attributes of definitions with only docstrings
  tests/unittest_builder.py
Labels: bug, enhancement

#1417 Use ``functools.cached_property`` on 3.8+ and for ``TYPE_CHECKING``
  ChangeLog
  astroid/decorators.py
  astroid/mixins.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/objects.py
  tests/unittest_decorators.py
Labels: maintenance

#1415 Add some typing to ``astroid.inference``
  astroid/inference.py
Labels: maintenance

#1271 Fix F403 wildcart import used in astroid/__init__.py
  .pre-commit-config.yaml
  astroid/__init__.py
  astroid/exceptions.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/rebuilder.py
  pylintrc
  tests/unittest_builder.py
  tests/unittest_lookup.py
  tests/unittest_nodes.py
  tests/unittest_scoped_nodes.py
Labels: high-effort, maintenance

#1435 Small typing improvements
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/protocols.py
  astroid/rebuilder.py
Labels: maintenance

#1443 Introduce end-of-line normalization
  .gitattributes
  astroid/brain/brain_scipy_signal.py
  tests/testdata/python3/data/recursion.py
Labels: maintenance

#1445 Apply autoformat with prettier on .copyrite_aliases
  .copyrite_aliases
Labels: maintenance

#1444 Limit concurrent jobs [ci]
  .github/workflows/ci.yaml
Labels: maintenance

#1446 Increase timeout limts [ci]
  .github/workflows/ci.yaml
Labels: maintenance

#1447 Replace sys.version_info checks with getattr [rebuilder]
  astroid/rebuilder.py
Labels: maintenance

#1434 Deprecate accessing the ``doc`` attribute on nodes
  ChangeLog
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_builder.py
  tests/unittest_nodes.py
  tests/unittest_raw_building.py
  tests/unittest_scoped_nodes.py
Labels: enhancement, maintenance

#1437 Pass ``doc_node`` to postinit of all ``PartialFunction`` constructors
  astroid/brain/brain_functools.py
  astroid/objects.py
  tests/unittest_brain.py
Labels: enhancement

#1448 Make ``_docs_dedent`` use ``doc_node``
  astroid/nodes/as_string.py
Labels: maintenance

#1433 Do not use ``doc`` attribute internally
  astroid/interpreter/objectmodel.py
  astroid/nodes/node_ng.py
  astroid/raw_building.py
  tests/unittest_scoped_nodes.py
Labels: maintenance

#1452 Fix typing and ``postinit`` in ``build_class``
  astroid/raw_building.py
Labels: maintenance

#1459 Replace platform import
  astroid/const.py
  astroid/modutils.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/rebuilder.py
  tests/unittest_builder.py
  tests/unittest_inference.py
  tests/unittest_manager.py
  tests/unittest_nodes.py
  tests/unittest_nodes_lineno.py
  tests/unittest_raw_building.py
  tests/unittest_scoped_nodes.py
Labels: maintenance

#1451 No longer pass ``doc`` to various node constructors
  astroid/builder.py
  astroid/raw_building.py
  astroid/rebuilder.py
  doc/extending.rst
Labels: documentation, maintenance

#1455 Do no pass ``doc`` attribute to ``nodes.Module`` in tests
  tests/unittest_brain.py
  tests/unittest_scoped_nodes.py
Labels: maintenance

#1458 Do no pass ``doc`` attribute to ``nodes.ClassDef`` in tests
  astroid/brain/brain_argparse.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/raw_building.py
Labels: maintenance

#1460 Move ``builtin_lookup`` out of main ``scoped_nodes`` file
  astroid/nodes/scoped_nodes/__init__.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/nodes/scoped_nodes/utils.py
Labels: enhancement, maintenance

#1462 Remove ``_ListComp``
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: maintenance

#1463 Move Mixin classes out of main ``scoped_nodes`` file
  astroid/nodes/scoped_nodes/__init__.py
  astroid/nodes/scoped_nodes/mixin.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: maintenance

#1453 Deprecate passing the ``doc`` argument
  ChangeLog
  astroid/decorators.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_scoped_nodes.py
Labels: enhancement

#1456 Deprecate passing ``doc`` to ``PartialFunction``
  astroid/objects.py
Labels: maintenance

#1457 Deprecate passing ``doc`` to ``Property``
  astroid/objects.py
Labels: maintenance

#1464 Minor changes
  astroid/nodes/node_ng.py
  astroid/rebuilder.py
Labels: maintenance

#1450 Add missing `shape` parameter to numpy methods
  ChangeLog
  astroid/brain/brain_numpy_core_numeric.py
  requirements_test_brain.txt
  tests/unittest_brain_numpy_core_numeric.py
Labels: bug, brain

#1465 Bump max pin on `wrapt`
  ChangeLog
  setup.cfg
Labels: maintenance

#1438 New release process
  doc/release.md
  tbump.toml
Labels: documentation, maintenance

#1466 Upgrade mypy to 0.940
  .pre-commit-config.yaml
  requirements_test_pre_commit.txt
  setup.cfg
  tests/unittest_nodes.py
  tests/unittest_nodes_lineno.py
Labels: dependency

#1468 Move ``InferFn`` to ``typing.py``
  astroid/inference_tip.py
  astroid/nodes/node_ng.py
  astroid/typing.py
Labels: maintenance

#1470 Add conditional overloads [TreeRebuilder]
  astroid/rebuilder.py
Labels: maintenance

#1472 Promoted ``getattr()`` from FunctionDef to Lambda
  ChangeLog
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_inference.py
  tests/unittest_scoped_nodes.py
Labels: crash

#1471 Fix typing in ``context.py``
  astroid/context.py
Labels: maintenance

#1477 Fix crash on direct inference via nodes.FunctionDef._infer
  ChangeLog
  astroid/inference.py
  astroid/nodes/node_ng.py
  tests/unittest_inference.py
Labels: crash

#1485 Fix incorrect xfailed test
  tests/unittest_inference.py
Labels: maintenance

#1488 Update ``pylint`` to ``2.13``
  astroid/inference.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/rebuilder.py
  requirements_test.txt
  requirements_test_pre_commit.txt
  tbump.toml
Labels: maintenance

#1489 Avoid adding the name of a parent namedtuple to child's locals
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  tests/unittest_brain.py
Labels: needs-backport, pylint-tested
