Repository pylint-dev/astroid, pull requests merged in 2022-07, with the labels that each got.

#1413 Refactor field inference to ``_get_namedtuple_fields``
  astroid/brain/brain_namedtuple_enum.py
Labels: Maintenance

#1681 Add typing and small refactors to ``namedtuple`` brain
  astroid/brain/brain_namedtuple_enum.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: Maintenance

#1682 Prevent creating `Instance` that proxies another `Instance` when inferring `__new__(cls)`
  ChangeLog
  astroid/bases.py
  tests/unittest_inference.py
Labels: Bug 🪳, inference

#1606 Add ``__new__`` and ``__call__`` to``ObjectModel`` and ``ClassModel``
  ChangeLog
  astroid/bases.py
  astroid/interpreter/objectmodel.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_objects.py
Labels: Enhancement ✨, pylint-tested

#1656 Add brain for numpy core module ``einsumfunc``.
  ChangeLog
  astroid/brain/brain_numpy_core_einsumfunc.py
  tests/unittest_brain_numpy_core_einsumfunc.py
Labels: Enhancement ✨

#1688 Fix ``pylint`` issues and remove useless disables
  astroid/exceptions.py
  tests/unittest_brain_numpy_core_einsumfunc.py
  tests/unittest_lookup.py
  tests/unittest_nodes.py
Labels: Maintenance

#1686 Fix order of attribute look ups for Super
  astroid/objects.py
  tests/unittest_inference.py
  tests/unittest_objects.py
Labels: Bug 🪳, pylint-tested, Unreleased

#1687 Add ``__init__`` to the ``ObjectModel`` and return ``BoundMethods``
  ChangeLog
  astroid/interpreter/objectmodel.py
  tests/unittest_object_model.py
  tests/unittest_objects.py
Labels: Enhancement ✨, pylint-tested

#1689 Call ``Instance.__init__`` in ``nodes.Const``
  astroid/bases.py
  astroid/nodes/node_classes.py
Labels: Bug 🪳, Unreleased

#1690 Fix a crash involving properties within ``try ... except`` blocks
  ChangeLog
  astroid/inference.py
  tests/unittest_scoped_nodes.py
Labels: Needs backport, Crash 💥

#1695 Fix a crash involving properties within `if` blocks
  ChangeLog
  astroid/inference.py
  tests/unittest_scoped_nodes.py
Labels: Needs backport, Crash 💥

#1696 Fix a crash when `None` participates in a `**` expression
  ChangeLog
  astroid/protocols.py
  tests/unittest_protocols.py
Labels: Needs backport, Regression, Crash 💥

#1697 Fix a crash when inferring old-style string formatting (`%`) using tuples
  ChangeLog
  astroid/inference.py
  tests/unittest_inference.py
Labels: Needs backport, Regression, Crash 💥

#1699 Make the potential attributes of all exceptions explicit
  astroid/exceptions.py
Labels: Needs backport, Maintenance

#1701 Only infer module operations on string ``Const`` nodes
  ChangeLog
  astroid/inference.py
  tests/unittest_inference.py
Labels: Bug 🪳, Needs backport, Crash 💥

#1702 Prevent applying boolean ops to `NotImplemented`
  astroid/protocols.py
  tests/unittest_inference.py
Labels: Needs backport, Maintenance

#1704 Bump runners to ``3.10``
  .github/workflows/ci.yaml
  .github/workflows/release-tests.yml
  .github/workflows/release.yml
Labels: Maintenance

#1705 Catch RecursionError in ``raise_if_nothing_inferred``
  ChangeLog
  astroid/decorators.py
  tests/unittest_regrtest.py
Labels: Needs backport, Crash 💥

#1719 Fixes #1717 - ignore FutureWarnings which are raised by pandas
  CONTRIBUTORS.txt
  ChangeLog
  astroid/raw_building.py
  tests/testdata/python3/data/fake_module_with_warnings.py
  tests/unittest_raw_building.py
Labels: Needs backport, Crash 💥

#1723 Remove ``setup.py``
  setup.py
Labels: Maintenance
