Repository pylint-dev/astroid, pull requests merged in 2022-10, with the labels that each got.

#1813 Remove unnecessary ``xfail`` from tests
  tests/unittest_inference.py
Labels: Maintenance

#1812 Fix regression in the creation of the ``__init__`` of dataclasses
  ChangeLog
  astroid/brain/brain_dataclasses.py
  astroid/nodes/node_classes.py
  tests/unittest_brain_dataclasses.py
Labels: Bug 🪳

#1820 Add ``_value2member_map_`` member to the ``enum`` brain.
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  tests/unittest_scoped_nodes.py
Labels: Bug 🪳, Needs backport

#1822 Release branch 2.12.11
  CONTRIBUTORS.txt
  ChangeLog
  astroid/__pkginfo__.py
  script/.contributors_aliases.json
  tbump.toml
Labels: Maintenance

#1831 Replace deprecated set-output commands [ci]
  .github/workflows/ci.yaml
Labels: Maintenance

#1827 Update the ``hashlib`` brain ``hash.digest`` & ``hash.hexdigest`` methods.
  ChangeLog
  astroid/brain/brain_hashlib.py
  tests/unittest_brain.py
Labels: Bug 🪳, Needs backport, Brain 🧠

#1833 Prevent a crash when a module's ``__path__`` is missing
  ChangeLog
  astroid/interpreter/_import/util.py
  tests/unittest_manager.py
Labels: Needs backport

#1836 Fix detecting invalid metaclasses
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_scoped_nodes.py
Labels: Bug 🪳

#1835 Move changelog entry for dataclasses regression
  ChangeLog
Labels: Documentation :green_book:, Needs backport

#1834 Fix `getattr` inference with empty annotation assignments
  ChangeLog
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_scoped_nodes.py
Labels: Bug 🪳, Needs backport

#1842 Fix windows cache key [ci]
  .github/workflows/ci.yaml
Labels: Maintenance

#1845 Use relative paths in `create_contributor_list.py`
  script/create_contributor_list.py
Labels: Maintenance

#1846 Confirm changes before tbump commit
  tbump.toml
Labels: Needs backport, Maintenance

#1854 Run tests with Python 3.11.0
  .github/workflows/ci.yaml
Labels: Maintenance

#1855 Add PyPI deployment environment [ci]
  .github/workflows/release.yml
Labels: Needs backport, Maintenance

#1857 Use Python 3.9 for virtualenv-15-windows-test job
  .github/workflows/release-tests.yml
Labels: Maintenance
