Repository pylint-dev/astroid, pull requests merged in 2022-12, with the labels that each got.

#1897 Handle properties in dataclasses correctly
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: Needs backport, dataclasses

#1892 Fix crash if numpy doesn't have version
  ChangeLog
  astroid/brain/brain_numpy_utils.py
Labels: Crash 💥

#1887 Add some inference annotations
  astroid/decorators.py
  astroid/inference.py
  astroid/interpreter/dunder_lookup.py
  astroid/nodes/_base_nodes.py
  astroid/protocols.py
Labels: Maintenance

#1903 Inference tip str.format transformation: handle AttributeError during str.format template evaluation
  ChangeLog
  astroid/brain/brain_builtin_inference.py
  tests/unittest_brain_builtin.py
Labels: Bug 🪳, Needs review 🔍

#1888 Misc type stuff
  astroid/_ast.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_uuid.py
  astroid/brain/helpers.py
  astroid/transforms.py
  astroid/util.py
Labels: Maintenance

#1918 [github actions] Add the same backporting job than in pylint
  .github/workflows/backport.yml
Labels: Maintenance, backport maintenance/2.12.x

#1919 [github actions] Test for the backporting actions
  ChangeLog
Labels: Maintenance, backport maintenance/2.12.x

#1920 Upgrade contributor test backport
  CONTRIBUTORS.txt
Labels: Maintenance, backport maintenance/2.12.x

#1912 Remove deprecated `ignore-mixin-members` pylint option
  pylintrc
Labels: Maintenance

#1898 Handle init=False with defaults in dataclasses
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: Bug 🪳, dataclasses, backport maintenance/2.12.x

#1899 Handle the effect of ``kw_only=True`` in dataclass fields correctly
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: Bug 🪳, dataclasses, backport maintenance/2.12.x

#1909 [pre-commit] Trying out black 23.1a1
  .pre-commit-config.yaml
  astroid/brain/brain_namedtuple_enum.py
  astroid/builder.py
  astroid/interpreter/objectmodel.py
  astroid/protocols.py
  astroid/raw_building.py
  astroid/rebuilder.py
  requirements_test_pre_commit.txt
  tests/unittest_inference.py
Labels: dependency

#1931 brain tip for numpy masked_invalid
  ChangeLog
  astroid/brain/brain_numpy_ma.py
  tests/unittest_brain_numpy_ma.py
Labels: Needs review 🔍, Brain 🧠

#1932 Cache `ClassDef._metaclass_lookup_attribute`
  astroid/manager.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_manager.py
Labels: topic-performance, pylint-tested
