Repository pylint-dev/astroid, pull requests merged in 2022-06, with the labels that each got.

#1586 Add ``typing-extensions`` to test dependencies
  requirements_test_min.txt
  tests/unittest_scoped_nodes.py
Labels: maintenance

#1584 Move ``3.11`` to standard test job
  .github/workflows/ci.yaml
Labels: maintenance

#1589 Add typing to function in ``raw_building``
  astroid/raw_building.py
Labels: maintenance

#1591 Add typing to function in ``raw_building``
  astroid/raw_building.py
Labels: maintenance

#1592 Create ``_get_args_info_from_callable``
  astroid/raw_building.py
Labels: maintenance

#1594 Allow passing arguments as ``None`` to ``FunctionDef`` builder
  astroid/nodes/node_classes.py
  astroid/raw_building.py
  tests/unittest_builder.py
Labels: maintenance

#1196 Infer the actual unpacked value on Dict's getitem()
  ChangeLog
  astroid/nodes/node_classes.py
  tests/unittest_python3.py
Labels: enhancement, inference

#1590 Infer instances of builtins created by `__new__()`
  ChangeLog
  astroid/bases.py
  tests/unittest_inference.py
Labels: enhancement, pylint-tested, inference

#1580 Add partial typing to NodeNG.infer
  astroid/nodes/node_ng.py
Labels: maintenance

#1442 Add `pathlib` brain to handle `.parents` inference
  ChangeLog
  astroid/brain/brain_pathlib.py
  tests/unittest_brain_pathlib.py
Labels: bug, needs review, python 3.10

#1541 Add typing to ``NodeNG._infer`` and associated nodes
  astroid/inference.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/objects.py
Labels: maintenance

#1381 Add missing ssl enums to astroid/brain
  ChangeLog
  astroid/brain/brain_ssl.py
  tests/test_brain_ssl.py
  tests/unittest_regrtest.py
Labels: brain

#1596 Move TreeRebuilder overloads behind TYPE_CHECKING guard
  astroid/rebuilder.py
Labels: maintenance

#1599 Do not use deprecated ``zipimport.load_module`` on ``PY310``
  astroid/interpreter/_import/spec.py
Labels: maintenance

#1597 Create and use ``InferenceResult``
  astroid/bases.py
  astroid/nodes/node_ng.py
  astroid/typing.py
Labels: maintenance

#1608 `argparse` brain: avoid spurious addition of "namespace" to function locals
  ChangeLog
  astroid/brain/brain_argparse.py
  tests/unittest_brain_argparse.py
Labels: bug, needs-backport, brain

#1609 Use new Pypy version identifier for setup-python action
  .github/workflows/ci.yaml
Labels: maintenance

#1602 Infer calls to ``str.format``
  ChangeLog
  astroid/brain/brain_builtin_inference.py
  tests/unittest_brain_builtin.py
  tests/unittest_inference.py
  tests/unittest_scoped_nodes.py
Labels: bug, enhancement

#1614 Fix ``str.format`` with ``KeyError``
  astroid/brain/brain_builtin_inference.py
  tests/unittest_brain_builtin.py
Labels: crash

#1616 Infer calls to ``format()`` on variables that are strings
  ChangeLog
  astroid/brain/brain_builtin_inference.py
  tests/unittest_brain_builtin.py
Labels: enhancement

#1624 Only initialize importers when they are required
  astroid/interpreter/_import/spec.py
  astroid/manager.py
Labels: topic-performance

#1626 Add strict typing to ``modutils``
  astroid/interpreter/_import/spec.py
  astroid/modutils.py
Labels: maintenance

#1628 Resolve typing issue in ``manager.py``
  astroid/manager.py
  astroid/modutils.py
Labels: maintenance

#1617 Infer modulo operations on strings
  ChangeLog
  astroid/inference.py
  tests/unittest_inference.py
Labels: enhancement

#1631 Fix typing issue for ``NodeNG._fixed_source_line``
  astroid/nodes/node_ng.py
Labels: maintenance

#1632 Make ``LookupMixIn`` inherit from ``NodeNG``
  .coveragerc
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/mixin.py
Labels: maintenance

#1634 Fix small typing issues
  astroid/nodes/node_classes.py
  astroid/raw_building.py
Labels: pylint-tested, maintenance

#1638 Add typing to ``NodeNG.root``
  astroid/nodes/node_ng.py
Labels: maintenance

#1637 Correct typing of ``relative_to_absolute_name``
  astroid/mixins.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: maintenance

#1639 Make inheritance pattern of ``BlockNodes`` explicit
  astroid/mixins.py
  astroid/nodes/_base_nodes.py
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: maintenance

#1641 Make inheritance pattern of various base nodes explicit
  astroid/mixins.py
  astroid/nodes/_base_nodes.py
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: maintenance

#1642 Make inheritance pattern of ``AssignTypeNodes`` explicit
  astroid/mixins.py
  astroid/nodes/_base_nodes.py
  astroid/nodes/node_classes.py
Labels: maintenance

#1644 Resolve typing issues in ``protocols.py``
  astroid/protocols.py
Labels: maintenance

#1636 Type safe_infer, Proxy.infer and fix InferenceResult
  astroid/bases.py
  astroid/helpers.py
  astroid/typing.py
Labels: maintenance

#1610 Avoid performing `**` operations on values greater than 1e5
  ChangeLog
  astroid/protocols.py
  tests/unittest_protocols.py
Labels: topic-performance

#1652 Fix type issue in TreeRebuilder added with change to Dict.items
  astroid/rebuilder.py
Labels: maintenance

#1651 Add typing to ``Name._infer`` and ``AssignName.infer_lhs``
  astroid/inference.py
  astroid/nodes/node_classes.py
Labels: maintenance

#1650 Add typing to ``const_factory``
  astroid/nodes/node_classes.py
  astroid/raw_building.py
Labels: pylint-tested, Maintenance

#1622 Revert #893: Avoid setting a Call as a base for classes from `six.with_metaclass()`
  ChangeLog
  astroid/brain/brain_six.py
  tests/unittest_brain.py
Labels: Bug 🪳

#1655 Fix typing of ``_infer`` to allow a return value in the ``Generator``
  astroid/bases.py
  astroid/nodes/node_ng.py
  astroid/objects.py
Labels: Maintenance

#1658 Type ``_infer`` of ``BoolOp``
  astroid/inference.py
Labels: Maintenance

#1657 Type ``_infer`` of Attribute, AssignAttr, Global and Subscript
  astroid/inference.py
  astroid/nodes/node_classes.py
Labels: Maintenance

#1661 Type ``_infer`` of the last nodes
  astroid/inference.py
Labels: Maintenance

#1659 Type ``_infer`` of binary operation nodes
  astroid/inference.py
  astroid/nodes/node_classes.py
Labels: Maintenance

#1662 `hashlib`: Add support for `usedforsecurity` keyword
  ChangeLog
  astroid/brain/brain_hashlib.py
  tests/unittest_brain.py
Labels: Bug 🪳, Needs backport, brain, pylint-tested

#1665 Refs #1662: Condition `usedforsecurity` support on Py3.9+
  astroid/brain/brain_hashlib.py
  tests/unittest_brain.py
Labels: Bug 🪳, Needs backport, brain

#1663 Fix inference of living container elements
  ChangeLog
  astroid/nodes/node_classes.py
  tests/test_stdlib.py
Labels: Enhancement ✨

#1664 Type ``infer_unary_op``
  astroid/nodes/node_classes.py
  astroid/protocols.py
  astroid/typing.py
Labels: Maintenance

#1668 Type ``_infer`` of Attribute, AssignAttr, Global and Subscript (#1657)
  astroid/inference.py
  astroid/nodes/node_classes.py
Labels: Maintenance

#1670 Improve packaging [PEP 517 + 621]
  .flake8
  .github/workflows/release.yml
  MANIFEST.in
  pyproject.toml
  setup.cfg
  setup.py
Labels: Maintenance

#1673 Add typing to ``Proxy._proxied``
  astroid/bases.py
Labels: Maintenance

#1674 Add typing to ``_function_type`` and ``_build_proxy_class``
  astroid/helpers.py
  astroid/manager.py
  astroid/typing.py
Labels: Maintenance

#1676 Add typing to ``ClassDef.ancestors``
  astroid/bases.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: Maintenance

#1675 Add typing to ``ClassDef._metaclass``
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: Maintenance

#1679 Update `subprocess.Popen` args for Python 3.9+
  ChangeLog
  astroid/brain/brain_subprocess.py
Labels: Bug 🪳, Enhancement ✨, Needs backport, python 3.9
