Repository pylint-dev/astroid, pull requests merged in 2022-02, with the labels that each got.

#1324 Use ``sysconfig`` to determine ``stdlib`` paths for ``PyPy``
  astroid/modutils.py
Labels: maintenance

#1323 Use ``sysconfig.get_path`` instead of ``distutils`` to find ``stdlib``
  ChangeLog
  astroid/modutils.py
Labels: maintenance

#1367 Fix crash on inference of ``__dict__.items()`` of an imported module
  ChangeLog
  astroid/inference.py
  tests/testdata/python3/data/module_dict_items_call/models.py
  tests/testdata/python3/data/module_dict_items_call/test.py
  tests/unittest_inference.py
Labels: crash

#1360 Fix inference of ``self`` in a list or tuple within bin. ops.
  ChangeLog
  astroid/protocols.py
  tests/unittest_inference.py
Labels: bug

#1384 Remove unused tryfinally builder function
  astroid/rebuilder.py
Labels: maintenance

#1387 Improve order of keyword-only args in argnames()
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_scoped_nodes.py
Labels: enhancement

#1391 Add ``is_dataclass`` attribute to ``ClassDef``
  ChangeLog
  astroid/brain/brain_dataclasses.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_brain_dataclasses.py
Labels: enhancement

#1397 Add regression test for changes to support hermetic interpreters
  tests/unittest_builder.py
Labels: maintenance

#1395 Fix ``ClassDef.fromlineno`` for Python < 3.8
  ChangeLog
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_builder.py
Labels: bug

#1400 Fix crash inferring on NewType named with f-string
  ChangeLog
  astroid/brain/brain_typing.py
  tests/unittest_brain.py
Labels: crash

#1401 Fix incorrect test skip message
  astroid/test_utils.py
Labels: maintenance

#1326 Use ``importlib`` instead of ``pkg_resources`` for determining namespace packages
  astroid/const.py
  astroid/interpreter/_import/util.py
Labels: pylint-tested, maintenance

#1392 Fix recursion error for inference of self-referencing class attribute
  ChangeLog
  astroid/inference_tip.py
  tests/unittest_inference.py
Labels: crash

#1409 Revert "Use ``importlib`` instead of ``pkg_resources`` for determining namespace packages"
  astroid/interpreter/_import/util.py
Labels: maintenance

#1408 Add ``Position`` to the ``__init__`` of ``nodes``
  astroid/nodes/__init__.py
Labels: enhancement, maintenance

#1407 Limit expensive decorator function
  ChangeLog
  astroid/decorators.py
  astroid/util.py
Labels: topic-performance

#1386 Restore custom `distutils` handling for resolving paths to submodules.
  .github/workflows/release-tests.yml
  ChangeLog
  astroid/interpreter/_import/spec.py
  doc/release.md
Labels: bug

#1215 Refactor: Stop adding arbitrary attributes to module obj when building
  astroid/builder.py
Labels: pylint-tested, maintenance

#1351 Changed NodeNG.tolineno to use end_lineno when it is available
  ChangeLog
  astroid/nodes/node_ng.py
  astroid/rebuilder.py
  tests/unittest_builder.py
  tests/unittest_nodes_lineno.py
  tests/unittest_scoped_nodes.py
Labels: enhancement

#1412 Add some typing to ``NamedTuple`` brain
  astroid/brain/brain_namedtuple_enum.py
Labels: maintenance

#1276 Add doc_node attribute
  ChangeLog
  astroid/const.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/rebuilder.py
  tests/unittest_nodes.py
  tests/unittest_scoped_nodes.py
Labels: enhancement
