Repository pylint-dev/astroid, pull requests merged in 2022-05, with the labels that each got.

#1529 Improve recognition of ``_io`` module during bootstrapping on ``PyPy``
  astroid/raw_building.py
  tests/unittest_inference.py
Labels: bug, needs-backport, pylint-tested

#1476 Define ``generators`` on ``ComprehensionScope``
  astroid/nodes/scoped_nodes/mixin.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: maintenance

#1528 Let `AstroidManager.clear_cache` reload brain plugins
  ChangeLog
  astroid/__init__.py
  astroid/const.py
  astroid/manager.py
  tests/resources.py
  tests/unittest_manager.py
Labels: bug

#1543 Define ``_infer`` instead of ``infer`` on subclasses of ``NodeNG``
  astroid/nodes/node_classes.py
  astroid/objects.py
Labels: maintenance

#1544 Prevent special case for `virtualenv`'s patching of `distutils` from catching other submodules
  ChangeLog
  astroid/interpreter/_import/spec.py
  tests/unittest_regrtest.py
Labels: needs-backport, regression, pylint-tested

#1521 Let `AstroidManager.clear_cache` act on other caches
  astroid/inference.py
  astroid/interpreter/objectmodel.py
  astroid/manager.py
  astroid/modutils.py
  astroid/nodes/node_classes.py
  tests/unittest_manager.py
  tests/unittest_modutils.py
Labels: maintenance

#1546 chore: Set permissions for GitHub actions
  .github/workflows/release-tests.yml
  .github/workflows/release.yml
Labels: maintenance

#1547 Fix crash while obtaining `object_type()` of an `Unknown` node
  ChangeLog
  astroid/helpers.py
  tests/unittest_helpers.py
Labels: needs-backport, crash, pylint-tested

#1542 Require Python 3.7.2
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  ChangeLog
  astroid/brain/brain_crypt.py
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_re.py
  astroid/brain/brain_subprocess.py
  astroid/brain/brain_typing.py
  astroid/const.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/rebuilder.py
  setup.cfg
  tests/unittest_brain.py
  tests/unittest_brain_dataclasses.py
  tests/unittest_scoped_nodes.py
  tox.ini
Labels: maintenance

#1540 Infer returned value of .copy() method for collections
  ChangeLog
  astroid/brain/brain_builtin_inference.py
  tests/unittest_inference.py
Labels: brain

#1550 qt brain: Make slot argument optional for disconnect()
  ChangeLog
  astroid/brain/brain_qt.py
  tests/unittest_brain_qt.py
Labels: needs-backport, brain

#1554 Remove some test skips
  tests/unittest_builder.py
  tests/unittest_nodes.py
Labels: maintenance

#1553 Update pylint to 2.14.0b1
  astroid/arguments.py
  astroid/brain/brain_gi.py
  astroid/builder.py
  astroid/manager.py
  astroid/protocols.py
  astroid/rebuilder.py
  pylintrc
  requirements_test_pre_commit.txt
  tests/unittest_inference.py
Labels: maintenance, dependency

#1555 Update typing for Python 3.7 (1)
  astroid/_ast.py
  astroid/arguments.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_functools.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_numpy_utils.py
  astroid/brain/brain_re.py
  astroid/brain/brain_typing.py
  astroid/builder.py
  astroid/context.py
  astroid/exceptions.py
  astroid/filter_statements.py
  astroid/inference.py
  astroid/inference_tip.py
  astroid/interpreter/_import/spec.py
  astroid/interpreter/objectmodel.py
  astroid/manager.py
  astroid/mixins.py
  astroid/modutils.py
  astroid/nodes/as_string.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/mixin.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/nodes/scoped_nodes/utils.py
  astroid/objects.py
  astroid/protocols.py
  astroid/raw_building.py
  astroid/rebuilder.py
  astroid/test_utils.py
  astroid/transforms.py
  astroid/typing.py
  pylintrc
  script/bump_changelog.py
  tests/resources.py
  tests/unittest_brain.py
  tests/unittest_brain_numpy_core_numeric.py
  tests/unittest_inference.py
  tests/unittest_nodes.py
  tests/unittest_nodes_position.py
  tests/unittest_objects.py
  tests/unittest_protocols.py
  tests/unittest_scoped_nodes.py
  tests/unittest_transforms.py
Labels: maintenance

#1556 Update typing for Python 3.7 (2)
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_functools.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_typing.py
  astroid/decorators.py
  astroid/inference.py
  astroid/inference_tip.py
  astroid/interpreter/_import/spec.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/nodes/scoped_nodes/utils.py
  astroid/objects.py
  astroid/protocols.py
  astroid/raw_building.py
  astroid/rebuilder.py
  astroid/test_utils.py
  pylintrc
  tests/unittest_inference.py
  tests/unittest_manager.py
  tests/unittest_protocols.py
  tests/unittest_transforms.py
Labels: maintenance

#1552 Fix ImportedModuleTests
  tests/unittest_inference.py
Labels: maintenance

#1557 Remove overload default values
  astroid/nodes/node_ng.py
Labels: maintenance

#1558 Fix 3.11 test
  ChangeLog
  tests/unittest_object_model.py
Labels: bug, python 3.11

#1561 Add Windows 3.11-dev job [ci]
  .github/workflows/ci.yaml
Labels: maintenance

#1564 Fix coverage performance issue with Python 3.11
  requirements_test.txt
Labels: python 3.11, maintenance

#1565 Add a bound to the inference tips cache
  ChangeLog
  astroid/inference_tip.py
Labels: topic-performance

#1566 Simplify namespace package detection on Python 3.7+
  astroid/interpreter/_import/spec.py
Labels: maintenance

#1311 Fix inference from nested unpacking of iterables
  ChangeLog
  astroid/protocols.py
  tests/unittest_inference.py
  tests/unittest_protocols.py
Labels: bug, pylint-tested

#1570 Revert "Add a bound to the inference tips cache (#1565)"
  ChangeLog
  astroid/inference_tip.py
Labels: regression, maintenance

#1563 Avoid a global state in `utils.builtin_lookup` and avoid reinstantiating `TransformVisitor`
  ChangeLog
  astroid/manager.py
  astroid/nodes/scoped_nodes/utils.py
  astroid/transforms.py
  tests/unittest_manager.py
Labels: bug

#1536 Remove dependency on `pkg_resources` from `setuptools`
  ChangeLog
  astroid/interpreter/_import/spec.py
  astroid/interpreter/_import/util.py
  astroid/manager.py
  setup.cfg
  tests/unittest_manager.py
Labels: topic-performance, high-effort, maintenance

#1572 Permit subscripting additional builtin classes
  ChangeLog
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_brain.py
  tests/unittest_inference.py
Labels: enhancement

#1514 Capture and log messages emitted by C modules when importing them
  ChangeLog
  astroid/modutils.py
  tests/unittest_modutils.py
Labels: enhancement

#1567 Detect builtins module on PyPy 3.9
  .github/workflows/ci.yaml
  ChangeLog
  astroid/interpreter/_import/spec.py
  astroid/raw_building.py
Labels: maintenance, PyPy

#1575 Provide first component of dotted path to namespace searches
  astroid/interpreter/_import/util.py
  tests/testdata/python3/data/parent_of_homonym/__init__.py
  tests/testdata/python3/data/parent_of_homonym/doc/README.md
  tests/testdata/python3/data/parent_of_homonym/doc/__init__.py
  tests/unittest_manager.py
Labels: crash

#1576 Revert #1575 and catch further `KeyError`s
  astroid/interpreter/_import/util.py
  tests/unittest_manager.py
Labels: enhancement

#1579 Special case `__main__` in `is_namespace()`
  astroid/interpreter/_import/util.py
  tests/unittest_manager.py
Labels: crash

#1581 More conservative interpretation of `PathFinder.find_spec()` failures
  astroid/interpreter/_import/util.py
  tests/unittest_manager.py
Labels: crash, pylint-tested
