Repository pylint-dev/astroid, pull requests merged in 2023-07, with the labels that each got.

#2231 Remove three mixin nodes from #2171
  astroid/__init__.py
  astroid/nodes/_base_nodes.py
  astroid/nodes/node_classes.py
Labels: pylint-tested, Maintenance, Unreleased

#2233 Fix ``typing`` issues in ``scoped_nodes.py``
  astroid/bases.py
  astroid/exceptions.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: Enhancement ✨

#2234 Fix deprecation of `rec` argument to `find_argname()`
  astroid/nodes/node_classes.py
Labels: Bug 🪳, Unreleased

#2235 Restore `AssignAttr.infer_lhs()`
  astroid/nodes/node_classes.py
  tests/test_inference.py
Labels: Unreleased, Crash 💥

#2238 Raise when a name is inferred twice with the same context
  astroid/nodes/node_classes.py
  tests/test_inference.py
Labels: Regression, Unreleased

#1867 Add `Try` node
  ChangeLog
  astroid/__init__.py
  astroid/node_classes.py
  astroid/nodes/__init__.py
  astroid/nodes/as_string.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/rebuilder.py
  tests/test_group_exceptions.py
  tests/test_nodes.py
  tests/test_nodes_lineno.py
Labels: Enhancement ✨, Needs review 🔍, High effort 🏋, ast, breaking-change

#2241 Add missing PEP 695 nodes to astroid.* and node_classes.*
  astroid/__init__.py
  astroid/node_classes.py
  astroid/nodes/__init__.py
Labels: python 3.12

#2242 Release branch 3.0.0a7
  astroid/__pkginfo__.py
  tbump.toml
Labels: Maintenance

#2243 [refactor] Remove variable for thing that never change in test_inference
  tests/test_inference.py
Labels: Maintenance

#2248 Correct references to removed TryExcept node
  ChangeLog
  astroid/nodes/node_classes.py
  doc/api/astroid.nodes.rst
  tests/test_inference.py
  tests/test_nodes_lineno.py
Labels: Maintenance

#2249 Remove references to removed OperationError shims
  doc/api/astroid.exceptions.rst
Labels: Documentation :green_book:

#2250 Let `TypeAlias` be a statement
  astroid/nodes/node_classes.py
  tests/test_type_params.py
Labels: Bug 🪳, Unreleased

#2252 Add `TypeAlias.assigned_stmts()`
  astroid/nodes/node_classes.py
  astroid/protocols.py
  tests/test_type_params.py
Labels: Bug 🪳, Enhancement ✨, python 3.12, Unreleased

#2239 Fix a crash when inferring a `typing.TypeVar` call.
  ChangeLog
  astroid/brain/brain_typing.py
  tests/brain/test_typing.py
Labels: backport maintenance/2.15.x

#2257 Use the inference cache when no context is provided
  ChangeLog
  astroid/nodes/node_ng.py
  tests/test_inference.py
Labels: topic-performance, pylint-tested

#2258 Avoid blaming formatting commits
  .git-blame-ignore-revs
Labels: Maintenance

#2240 Fix Arguments.arguments so it actually returns all arguments
  ChangeLog
  astroid/arguments.py
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/protocols.py
  astroid/rebuilder.py
  tests/test_nodes.py
Labels: Enhancement ✨

#2259 Fix inference involving `@functools.lru_cache` decorator
  ChangeLog
  astroid/brain/brain_functools.py
  tests/test_object_model.py
Labels: Bug 🪳, backport maintenance/2.15.x

#2261 fix default_value for kwonlyargs with no default
  astroid/nodes/node_classes.py
  tests/test_inference.py
Labels: Bug 🪳, Unreleased

#2264 Update type annotations of PEP 695 nodes
  astroid/nodes/node_classes.py
Labels: Maintenance, python 3.12, Unreleased
