Repository pylint-dev/astroid, pull requests merged in 2023-05, with the labels that each got.

#2162 Fix urllib3 tests following the release of v2.0.0
  requirements_full.txt
  tests/test_modutils.py
Labels: Maintenance

#2158 Complete cache key for inference tip
  ChangeLog
  astroid/inference_tip.py
  tests/brain/test_brain.py
  tests/test_regrtest.py
  tests/test_scoped_nodes.py
Labels: pylint-tested

#2166 Improve typing of inference functions
  astroid/inference.py
  astroid/inference_tip.py
  astroid/nodes/node_ng.py
  astroid/transforms.py
  astroid/typing.py
Labels: Maintenance

#2175 Remove pylint disables
  astroid/decorators.py
  astroid/manager.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  pylintrc
  tests/brain/test_typing_extensions.py
  tests/test_modutils.py
Labels: Maintenance

#2177 Handle `objects.Super` in `helpers.object_type()`
  ChangeLog
  astroid/helpers.py
  tests/test_helpers.py
Labels: Crash 💥, backport maintenance/2.15.x

#2178 Improve performance of `looks_like_numpy_member()`
  astroid/brain/brain_numpy_core_function_base.py
  astroid/brain/brain_numpy_core_multiarray.py
  astroid/brain/brain_numpy_core_numeric.py
  astroid/brain/brain_numpy_utils.py
Labels: topic-performance

#2185 Avoid duplicate inference results for `List[int]`
  astroid/brain/brain_typing.py
  tests/brain/test_brain.py
Labels: Regression, Unreleased

#2098 Check for call context in `PartialFunction.infer_call_result`
  astroid/objects.py
Labels: Enhancement ✨

#2187 Optimize `_compute_mro()`
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: topic-performance, pylint-tested
