Repository pylint-dev/astroid, pull requests merged in 2023-08, with the labels that each got.

#2268 Allow ``AsStringVisitor`` to visit ``objects.PartialFunction``
  ChangeLog
  astroid/nodes/as_string.py
  astroid/nodes/node_ng.py
  tests/brain/test_brain.py
Labels: Bug 🪳

#2271 Optimize ``qname()`` by catching an exception instead
  astroid/nodes/scoped_nodes/mixin.py
Labels: Enhancement ✨

#2270 Remove unnecessary if statement
  astroid/builder.py
Labels: Enhancement ✨, pylint-tested

#2269 Optimize root by not calling ``root()`` itself
  astroid/nodes/node_ng.py
Labels: Enhancement ✨

#2263 Exclude unassigned type-annotated class attributes from enum __members__ container
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  tests/brain/test_enum.py
Labels: Bug 🪳, backport maintenance/2.15.x

#2275 Use the python source for the datetime module in Python 3.12+
  astroid/brain/brain_datetime.py
  tests/brain/test_dateutil.py
Labels: python 3.12, Unreleased
