Repository pylint-dev/astroid, pull requests merged in 2023-09, with the labels that each got.

#2267 Register brains explicitly
  astroid/__init__.py
  astroid/astroid_manager.py
  astroid/brain/brain_argparse.py
  astroid/brain/brain_attrs.py
  astroid/brain/brain_boto3.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_collections.py
  astroid/brain/brain_crypt.py
  astroid/brain/brain_ctypes.py
  astroid/brain/brain_curses.py
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_datetime.py
  astroid/brain/brain_dateutil.py
  astroid/brain/brain_fstrings.py
  astroid/brain/brain_functools.py
  astroid/brain/brain_gi.py
  astroid/brain/brain_hashlib.py
  astroid/brain/brain_http.py
  astroid/brain/brain_hypothesis.py
  astroid/brain/brain_io.py
  astroid/brain/brain_mechanize.py
  astroid/brain/brain_multiprocessing.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_nose.py
  astroid/brain/brain_numpy_core_einsumfunc.py
  astroid/brain/brain_numpy_core_fromnumeric.py
  astroid/brain/brain_numpy_core_function_base.py
  astroid/brain/brain_numpy_core_multiarray.py
  astroid/brain/brain_numpy_core_numeric.py
  astroid/brain/brain_numpy_core_numerictypes.py
  astroid/brain/brain_numpy_core_umath.py
  astroid/brain/brain_numpy_ma.py
  astroid/brain/brain_numpy_ndarray.py
  astroid/brain/brain_numpy_random_mtrand.py
  astroid/brain/brain_pathlib.py
  astroid/brain/brain_pkg_resources.py
  astroid/brain/brain_pytest.py
  astroid/brain/brain_qt.py
  astroid/brain/brain_random.py
  astroid/brain/brain_re.py
  astroid/brain/brain_regex.py
  astroid/brain/brain_responses.py
  astroid/brain/brain_scipy_signal.py
  astroid/brain/brain_signal.py
  astroid/brain/brain_six.py
  astroid/brain/brain_sqlalchemy.py
  astroid/brain/brain_ssl.py
  astroid/brain/brain_subprocess.py
  astroid/brain/brain_threading.py
  astroid/brain/brain_type.py
  astroid/brain/brain_typing.py
  astroid/brain/brain_unittest.py
  astroid/brain/brain_uuid.py
  astroid/brain/helpers.py
  astroid/const.py
  astroid/manager.py
Labels: Enhancement ✨, pylint-tested

#2289 Exclude the ``_ignore_`` attribute from the ``__members__`` container.
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  tests/brain/test_enum.py
Labels: Bug 🪳, backport maintenance/2.15.x

#2244 [sys.argv] Make 'sys.argv' uninferable because it never is
  astroid/nodes/node_classes.py
  tests/test_inference.py
Labels: Bug 🪳, pylint-tested, backport maintenance/2.15.x

#2277 Infer user-defined enum classes by checking if the class is a subtype of ``enum.Enum``
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  tests/brain/test_enum.py
  tests/test_inference.py
Labels: Bug 🪳

#2299 Move misplaced changelog note
  ChangeLog
Labels: backport maintenance/2.15.x

#2300 Remove deprecated `node_classes`, `scoped_nodes`, and `mixins` modules
  ChangeLog
  astroid/__init__.py
  astroid/mixins.py
  astroid/node_classes.py
  astroid/scoped_nodes.py
Labels: Maintenance, breaking-change

#2301 [skip ci] Add missing news / merge maintenance branch into main following 2.15.7 release
  ChangeLog
Labels: Documentation :green_book:

#2302 Release branch 3.0.0b0
  CONTRIBUTORS.txt
  astroid/__pkginfo__.py
  tbump.toml
Labels: Maintenance

#2307 False positive ``unsubscriptable-object``
  ChangeLog
  astroid/brain/brain_typing.py
  tests/brain/test_typing.py
Labels: backport maintenance/2.15.x

#2303 Bump astroid to 3.0.0, update changelog
  ChangeLog
  astroid/__pkginfo__.py
  doc/upgrade_guide.rst
  doc/whatsnew.rst
  tbump.toml
Labels: Maintenance

#2311 Fix 3.0.x maintenance branch
  ChangeLog
  astroid/__pkginfo__.py
  doc/release.md
  tbump.toml
Labels: Documentation :green_book:, Maintenance
