Repository pylint-dev/astroid, pull requests merged in 2023-02, with the labels that each got.

#1752 Fix setuptools>=64 import hooks
  ChangeLog
  astroid/interpreter/_import/spec.py
  tests/unittest_modutils.py
Labels: Bug 🪳

#1741 Create ``UninferableBase``
  ChangeLog
  astroid/arguments.py
  astroid/bases.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_functools.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_typing.py
  astroid/builder.py
  astroid/constraint.py
  astroid/helpers.py
  astroid/inference.py
  astroid/inference_tip.py
  astroid/interpreter/objectmodel.py
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/protocols.py
  astroid/typing.py
  astroid/util.py
  doc/inference.rst
  tests/unittest_protocols.py
Labels: Bug 🪳, Maintenance

#2006 Add support for keyword only argument default values
  ChangeLog
  astroid/nodes/node_classes.py
  astroid/raw_building.py
  tests/unittest_nodes.py
Labels: Enhancement ✨, ast

#1963 Clean-up and fix tox's commands
  doc/api/base_nodes.rst
  pyproject.toml
  requirements_test.txt
  requirements_test_pre_commit.txt
  tox.ini
Labels: Maintenance

#2016 [doc] Use the real URL address of pylint's read the doc project
  pyproject.toml
Labels: Maintenance

#2018 Declare support for Python 3.11
  pyproject.toml
Labels: Maintenance, backport maintenance/2.14.x

#2024 Fix '_infer_str_format_call' crash when the string it analyses are uninferable
  ChangeLog
  astroid/brain/brain_builtin_inference.py
  tests/brain/test_builtin.py
Labels: Crash 💥, backport maintenance/2.14.x

#2015 Replace and deprecate modutils.is_standard_module()
  ChangeLog
  astroid/_backport_stdlib_names.py
  astroid/manager.py
  astroid/modutils.py
  tests/test_manager.py
  tests/test_modutils.py
Labels: Enhancement ✨

#2026 Burst more test brain into multiple brain tests files
  tests/brain/test_brain.py
  tests/brain/test_exceptions.py
  tests/brain/test_threading.py
Labels: Maintenance

#2029 Update ``FormattedValue.postinit`` and its brain
  ChangeLog
  astroid/brain/brain_fstrings.py
  astroid/nodes/node_classes.py
  astroid/rebuilder.py
Labels: Bug 🪳

#2023 fix `are_exclusive` function for walrus operator
  ChangeLog
  astroid/nodes/node_classes.py
  tests/test_utils.py
Labels: Bug 🪳

#2037 Ignore ``DeprecationWarnings`` for a test that tests old behaviour
  tests/testdata/python3/data/path_pkg_resources_1/package/__init__.py
Labels: Maintenance
