Repository pylint-dev/astroid, pull requests merged in 2023-06, with the labels that each got.

#2202 Harden get_module_part() against "."
  ChangeLog
  astroid/modutils.py
  tests/test_modutils.py
Labels: Crash 💥, backport maintenance/2.15.x

#2205 Suppress exception context describing a cache miss
  astroid/inference_tip.py
Labels: Minor 💅, Maintenance

#2204 Fix brain dict regression
  ChangeLog
  astroid/manager.py
  tests/test_regrtest.py
Labels: Bug 🪳, backport maintenance/2.15.x

#2208 Make `igetattr()` idempotent
  ChangeLog
  astroid/bases.py
  tests/test_inference.py
Labels: Bug 🪳, pylint-tested

#2209 Fix interrupted `InferenceContext` call chains
  ChangeLog
  astroid/arguments.py
  astroid/interpreter/dunder_lookup.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/test_inference.py
Labels: topic-performance, pylint-tested

#2198 Verify nodes' str() and repr() don't raise errors/warnings
  astroid/nodes/node_ng.py
  tests/test_nodes.py
Labels: Bug 🪳

#2210 Delay `astroid_bootstrapping()` until instantiating `AstroidBuilder`
  ChangeLog
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_nose.py
  astroid/builder.py
  astroid/raw_building.py
Labels: topic-performance, pylint-tested

#2217 Deprecate `rec` argument to `find_argname()`
  astroid/nodes/node_classes.py
Labels: topic-performance

#2222 Test on PyPy 3.10
  .github/workflows/ci.yaml
Labels: Maintenance, PyPy, backport maintenance/2.15.x

#2227 Small refactor after 3.12 support
  astroid/nodes/node_classes.py
Labels: Bug 🪳, Maintenance, Unreleased

#2224 Optimize exception handling in import_module()
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/test_scoped_nodes.py
Labels: topic-performance

#2228 Avoid expensive list/tuple multiplication operations
  ChangeLog
  astroid/protocols.py
  tests/test_protocols.py
Labels: Bug 🪳, topic-performance, backport maintenance/2.15.x
