Repository pylint-dev/astroid, pull requests merged in 2023-10, with the labels that each got.

#2314 Bump CI jobs to Python 3.12
  .github/workflows/ci.yaml
  .github/workflows/release.yml
  tox.ini
Labels: Maintenance

#2320 Add `assigned_stmts()` to PEP 695 nodes
  ChangeLog
  astroid/nodes/node_classes.py
  astroid/protocols.py
  tests/test_protocols.py
Labels: python 3.12, Crash 💥, backport maintenance/3.0.x

#2328 Disable test_crypt_brain on Python >= 3.13
  astroid/const.py
  tests/brain/test_brain.py
Labels: backport maintenance/3.0.x

#2331 Remove duplicative changelog entry
  ChangeLog
Labels: Documentation :green_book:, Maintenance

#2330 Visit PEP 695 nodes in `get_children()`
  ChangeLog
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/test_type_params.py
Labels: python 3.12
