Repository pylint-dev/astroid, pull requests merged in 2023-01, with the labels that each got.

#1595 Make ``Arguments.defaults`` ``None`` for uninferable signatures
  ChangeLog
  astroid/nodes/node_classes.py
  astroid/raw_building.py
  tests/unittest_builder.py
Labels: Enhancement ✨, Needs review 🔍

#1935 Use codecov and separate flags per OS
  .coveragerc
  .github/workflows/ci.yaml
  README.rst
  codecov.yml
  requirements_test.txt
  requirements_test_min.txt
Labels: Maintenance, backport maintenance/2.12.x

#1936 Backport: Use codecov and separate flags per OS (#1935)
  .coveragerc
  .github/workflows/ci.yaml
  README.rst
  codecov.yml
  requirements_test.txt
  requirements_test_min.txt
Labels: Maintenance

#1934 Regex brain
  ChangeLog
  astroid/brain/brain_regex.py
  requirements_test_brain.txt
  tests/test_brain_regex.py
Labels: Brain 🧠

#1941 bump minimal version of typing-extensions
  pyproject.toml
  requirements_test_min.txt
Labels: Crash 💥

#1943 Release branch 2.13.1
  CONTRIBUTORS.txt
  ChangeLog
  astroid/__pkginfo__.py
  script/.contributors_aliases.json
  tbump.toml
Labels: Maintenance

#1944 Remove typing_extensions from the tests requirements
  ChangeLog
  pyproject.toml
  requirements_test_min.txt
Labels: Bug 🪳, Maintenance, backport maintenance/2.13.x

#1947 Initial pass with ``pydocstringformatter``
  astroid/__init__.py
  astroid/_ast.py
  astroid/arguments.py
  astroid/bases.py
  astroid/brain/brain_boto3.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_dateutil.py
  astroid/brain/brain_functools.py
  astroid/brain/brain_hypothesis.py
  astroid/brain/brain_io.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_numpy_ma.py
  astroid/brain/brain_numpy_utils.py
  astroid/brain/brain_re.py
  astroid/brain/brain_regex.py
  astroid/brain/brain_responses.py
  astroid/brain/brain_six.py
  astroid/brain/brain_type.py
  astroid/brain/brain_typing.py
  astroid/builder.py
  astroid/context.py
  astroid/decorators.py
  astroid/exceptions.py
  astroid/filter_statements.py
  astroid/helpers.py
  astroid/inference.py
  astroid/inference_tip.py
  astroid/interpreter/_import/spec.py
  astroid/interpreter/dunder_lookup.py
  astroid/interpreter/objectmodel.py
  astroid/manager.py
  astroid/mixins.py
  astroid/modutils.py
  astroid/nodes/_base_nodes.py
  astroid/nodes/scoped_nodes/__init__.py
  astroid/nodes/scoped_nodes/utils.py
  astroid/protocols.py
  astroid/rebuilder.py
  astroid/util.py
Labels: Maintenance, backport maintenance/2.13.x

#1949 Initial pass with ``pydocstringformatter`` over tests
  tests/test_brain_regex.py
  tests/unittest_brain_ctypes.py
  tests/unittest_brain_dataclasses.py
  tests/unittest_brain_numpy_core_einsumfunc.py
  tests/unittest_brain_numpy_core_fromnumeric.py
  tests/unittest_brain_numpy_core_function_base.py
  tests/unittest_brain_numpy_core_multiarray.py
  tests/unittest_brain_numpy_core_numeric.py
  tests/unittest_brain_numpy_core_numerictypes.py
  tests/unittest_brain_numpy_core_umath.py
  tests/unittest_brain_numpy_ma.py
  tests/unittest_brain_numpy_ndarray.py
  tests/unittest_brain_numpy_random_mtrand.py
  tests/unittest_brain_qt.py
  tests/unittest_brain_unittest.py
  tests/unittest_builder.py
  tests/unittest_constraint.py
  tests/unittest_inference.py
  tests/unittest_inference_calls.py
  tests/unittest_lookup.py
  tests/unittest_manager.py
  tests/unittest_modutils.py
  tests/unittest_nodes.py
  tests/unittest_nodes_lineno.py
  tests/unittest_object_model.py
  tests/unittest_objects.py
  tests/unittest_protocols.py
  tests/unittest_regrtest.py
  tests/unittest_scoped_nodes.py
Labels: Maintenance, backport maintenance/2.13.x

#1792 First modification for pep237 with pydocstringformatter
  astroid/astroid_manager.py
  astroid/brain/brain_boto3.py
  astroid/brain/brain_collections.py
  astroid/brain/brain_ctypes.py
  astroid/brain/brain_numpy_core_einsumfunc.py
  astroid/brain/brain_numpy_utils.py
  astroid/brain/brain_unittest.py
  astroid/exceptions.py
  astroid/modutils.py
  astroid/nodes/node_ng.py
  astroid/objects.py
  astroid/test_utils.py
  astroid/transforms.py
Labels: Documentation :green_book:, Maintenance

#1956 [codecov] Use our own token to avoid being rate limited
  .github/workflows/ci.yaml
Labels: Maintenance

#1959 Fix a regression in 2.13.2 where a ``RunTimeError`` could be raised unexpectedly
  ChangeLog
  astroid/raw_building.py
  tests/testdata/python3/data/fake_module_with_broken_getattr.py
  tests/unittest_raw_building.py
Labels: Regression, Crash 💥, backport maintenance/2.13.x

#1964 Do not require typing_extensions on Python 3.11
  ChangeLog
  pyproject.toml
  tests/unittest_scoped_nodes.py
Labels: Bug 🪳, backport maintenance/2.13.x

#1967 Fix a false positive with user-defined `Enum` class
  .github/workflows/ci.yaml
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  tests/unittest_brain.py
Labels: Bug 🪳, backport maintenance/2.13.x

#1970 Fix order of overwritten attributes in inherited dataclasses
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: dataclasses, backport maintenance/2.13.x

#1971 Fix a false positive with user-defined `Enum` class (#1967)
  .github/workflows/ci.yaml
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  tests/unittest_brain.py
Labels: Bug 🪳, backport maintenance/2.13.x

#1972 Fix order of overwritten attributes in inherited dataclasses (#1970)
  ChangeLog
  astroid/brain/brain_dataclasses.py
  tests/unittest_brain_dataclasses.py
Labels: Maintenance

#1973 Fix issues with `typing_extensions.TypeVar`
  ChangeLog
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_typing.py
  requirements_test_brain.txt
  tests/unittest_brain.py
Labels: backport maintenance/2.13.x

#1979 Fix PyPy `ClassDef.fromlino` with decorators
  ChangeLog
  astroid/const.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/unittest_builder.py
  tests/unittest_nodes_position.py
Labels: ast, PyPy, backport maintenance/2.13.x

#1982 Preserve parent `CallContext` when inferring nested functions
  ChangeLog
  astroid/brain/brain_typing.py
  astroid/context.py
  astroid/inference.py
  astroid/protocols.py
  tests/unittest_brain.py
  tests/unittest_inference_calls.py
Labels: pylint-tested, inference, backport maintenance/2.13.x

#1984 Set higher recusion limit (2**12) for PyPy
  ChangeLog
  astroid/__init__.py
Labels: inference, backport maintenance/2.13.x

#1987 Skip recursion test on PyPy
  tests/unittest_inference.py
Labels: backport maintenance/2.13.x

#1989 Update isort to 5.12.0
  .pre-commit-config.yaml
  requirements_test_pre_commit.txt
Labels: Maintenance, dependency, backport maintenance/2.13.x

#1978 Possible fix for #1904.
  astroid/raw_building.py
  tests/unittest_raw_building.py
Labels: Enhancement ✨

#1977 Add support for binary union types - Python 3.10
  ChangeLog
  astroid/bases.py
  astroid/inference.py
  astroid/raw_building.py
  tests/unittest_inference.py
Labels: python 3.10, pylint-tested, inference

#1993 Fix dev requirements
  .github/workflows/ci.yaml
  requirements_test_pre_commit.txt
Labels: dependency, backport maintenance/2.13.x

#1994 Backport dev fix to maintenance for 3.8
  .github/workflows/ci.yaml
  requirements_test_pre_commit.txt
Labels: Maintenance

#1976 Add Lock to multiprocessing
  ChangeLog
  astroid/brain/brain_multiprocessing.py
  astroid/brain/brain_threading.py
  tests/unittest_brain.py
Labels: Bug 🪳, pylint-tested, backport maintenance/2.13.x

#1997 Release branch 2.13.4
  ChangeLog
  astroid/__pkginfo__.py
  tbump.toml
Labels: Maintenance

#1998 Release 2.14.0
  CONTRIBUTORS.txt
  ChangeLog
  astroid/__pkginfo__.py
  tbump.toml
Labels: Maintenance

#2000 Revert CallContext change since it caused a RecursionError regression
  ChangeLog
  astroid/brain/brain_typing.py
  astroid/context.py
  astroid/inference.py
  astroid/protocols.py
  tests/unittest_brain.py
  tests/unittest_inference.py
  tests/unittest_inference_calls.py
Labels: backport maintenance/2.14.x

#2004 Release 2.14.1
  ChangeLog
  astroid/__pkginfo__.py
  tbump.toml
Labels: Maintenance
