Repository pylint-dev/astroid, pull requests merged in 2023-03, with the labels that each got.

#2044 Cancel previous tests when pushing to PRs
  .github/workflows/ci.yaml
  .github/workflows/codeql-analysis.yml
Labels: Maintenance

#2028 Add Trystar nodes from python 3.11
  astroid/nodes/__init__.py
  astroid/nodes/node_classes.py
  astroid/rebuilder.py
  tests/test_group_exceptions.py
Labels: Enhancement ✨, python 3.11

#2045 Bump astroid to 2.15.0, update changelog
  CONTRIBUTORS.txt
  ChangeLog
  astroid/__pkginfo__.py
  tbump.toml
Labels: pylint-tested, Maintenance

#2051 Change `_get_assign_nodes()` to `cached_property`
  astroid/nodes/_base_nodes.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: pylint-tested, Maintenance

#2057 Upgrade pre-commit configuration and move to ruff
  .pre-commit-config.yaml
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/interpreter/_import/spec.py
  astroid/modutils.py
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  doc/conf.py
  pyproject.toml
  requirements_test_pre_commit.txt
  setup.cfg
  tests/test_inference.py
  tests/test_nodes.py
  tests/test_regrtest.py
Labels: Maintenance

#2049 Restore setting a Call as a base for classes from `six.with_metaclass()`
  ChangeLog
  astroid/brain/brain_six.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/brain/test_six.py
  tests/test_scoped_nodes.py
Labels: Bug 🪳, pylint-tested, backport maintenance/2.15.x
