Repository pylint-dev/astroid, pull requests merged in 2023-04, with the labels that each got.

#2059 Support attrs decorators even if they are imported from attrs
  ChangeLog
  astroid/brain/brain_attrs.py
  tests/brain/test_attr.py
Labels: Brain 🧠, backport maintenance/2.15.x

#2073 Support attrs decorators even if they are imported from attrs (#2059)
  ChangeLog
  astroid/brain/brain_attrs.py
  tests/brain/test_attr.py
Labels: Brain 🧠

#2076 Clean up the constructors of ``If`` and ``IfExp``
  ChangeLog
  astroid/nodes/node_classes.py
Labels: Enhancement ✨

#2080 Don't add typing stubs for packages that we only use in tests
  .pre-commit-config.yaml
  requirements_test.txt
  requirements_test_brain.txt
  tests/brain/test_attr.py
  tests/brain/test_dateutil.py
  tests/brain/test_regex.py
  tests/brain/test_six.py
  tests/test_inference.py
  tests/test_modutils.py
  tests/test_object_model.py
  tests/test_scoped_nodes.py
Labels: Maintenance

#2079 Fix constructors of ``Delete``
  ChangeLog
  astroid/nodes/node_classes.py
Labels: Enhancement ✨

#2081 Fix constructors of ``BinOp``
  ChangeLog
  astroid/nodes/node_classes.py
Labels: Enhancement ✨

#2077 Fix constructors of ``AssignName``
  ChangeLog
  astroid/interpreter/objectmodel.py
  astroid/nodes/node_classes.py
  astroid/raw_building.py
  tests/test_nodes.py
  tests/test_transforms.py
Labels: Enhancement ✨, pylint-tested

#2061 Mandatory fields for Assign
  ChangeLog
  astroid/nodes/node_classes.py
Labels: Enhancement ✨, pylint-tested

#2083 Fix constructors of ``Subscript``
  ChangeLog
  astroid/nodes/node_classes.py
Labels: Enhancement ✨

#2084 Fix constructors of ``Attribute``, ``DelAttr`` and ``AssignAttr``
  ChangeLog
  astroid/nodes/node_classes.py
Labels: Enhancement ✨

#2085 Fix constructors of ``Starred``, ``Compare``, ``UnaryOp`` and ``AnnAssign``
  ChangeLog
  astroid/nodes/node_classes.py
Labels: Enhancement ✨

#2087 Fix constructors of ``Arguments``
  ChangeLog
  astroid/interpreter/objectmodel.py
  astroid/nodes/node_classes.py
  astroid/raw_building.py
  tests/test_scoped_nodes.py
Labels: Enhancement ✨

#2088 Fix some line numbering related methods
  astroid/nodes/_base_nodes.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: Bug 🪳, Enhancement ✨

#2091 Mandatory fields for For
  ChangeLog
  astroid/nodes/node_classes.py
Labels: Enhancement ✨

#2095 Mandatory fields for While
  ChangeLog
  astroid/nodes/node_classes.py
Labels: Enhancement ✨

#2102 Fix typing issues with ``class_instance_as_index``
  astroid/helpers.py
Labels: Enhancement ✨

#2101 Type ``igetattr``
  astroid/bases.py
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/objects.py
Labels: Enhancement ✨

#2107 Mandatory fields for Decorators
  ChangeLog
  astroid/nodes/node_classes.py
Labels: Enhancement ✨, Maintenance

#2108 Mandatory field for Yield
  ChangeLog
  astroid/nodes/node_classes.py
  astroid/rebuilder.py
Labels: Enhancement ✨

#2109 Clean up If fields
  ChangeLog
  astroid/filter_statements.py
  astroid/nodes/node_classes.py
Labels: Enhancement ✨

#2117 Use `safe_infer` in `_unpack_args` and `_unpack_keywords`
  ChangeLog
  astroid/arguments.py
  tests/test_inference.py
Labels: Bug 🪳, pylint-tested

#2118 Fix infer_call_result() crash on methods called with_metaclass()
  ChangeLog
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/test_inference.py
Labels: Crash 💥

#2119 Port property-related workaround from `infer_functiondef` to `infer_property`
  ChangeLog
  astroid/brain/brain_builtin_inference.py
  tests/brain/test_builtin.py
Labels: Bug 🪳

#2121 Suppress UserWarning when finding module specs
  ChangeLog
  astroid/interpreter/_import/spec.py
  tests/test_manager.py
Labels: Bug 🪳, backport maintenance/2.15.x

#2115 Decouple ``FunctionDef`` and ``Lambda``
  ChangeLog
  astroid/helpers.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/test_scoped_nodes.py
Labels: Bug 🪳

#2126 Add ``attr.Factory`` to the ``attrs`` brain
  ChangeLog
  astroid/brain/brain_attrs.py
  tests/brain/test_attr.py
Labels: Bug 🪳

#2112 Clean up Lambda fields
  ChangeLog
  astroid/interpreter/objectmodel.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/objects.py
  astroid/raw_building.py
  tests/test_scoped_nodes.py
Labels: Enhancement ✨

#2130 Fix constructors of ``ClassDef``
  ChangeLog
  astroid/bases.py
  astroid/brain/brain_argparse.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_re.py
  astroid/brain/brain_regex.py
  astroid/brain/brain_typing.py
  astroid/nodes/scoped_nodes/mixin.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/raw_building.py
  tests/test_inference.py
  tests/test_manager.py
  tests/test_scoped_nodes.py
Labels: Enhancement ✨

#2133 Fix constructors of ``Module``
  ChangeLog
  astroid/builder.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/rebuilder.py
  tests/test_nodes_lineno.py
  tests/test_scoped_nodes.py
Labels: Enhancement ✨

#2132 Fix constructors of ``ComprehensionScopes``
  ChangeLog
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: Enhancement ✨

#2134 Fix some type issues in ``scoped_nodes``
  astroid/bases.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: Enhancement ✨

#2135 Reduce file system access in `ast_from_file()`
  ChangeLog
  astroid/manager.py
  astroid/modutils.py
Labels: topic-performance

#2137 Drop support for Python 3.7
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  .readthedocs.yaml
  ChangeLog
  astroid/__init__.py
  astroid/_ast.py
  astroid/bases.py
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_typing.py
  astroid/decorators.py
  astroid/interpreter/_import/spec.py
  astroid/interpreter/objectmodel.py
  astroid/modutils.py
  astroid/nodes/_base_nodes.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/objects.py
  astroid/rebuilder.py
  astroid/typing.py
  astroid/util.py
  pylintrc
  pyproject.toml
  requirements_test.txt
  tests/test_scoped_nodes.py
  tox.ini
Labels: Maintenance

#2140 Remove cachedproperty decorator
  ChangeLog
  astroid/decorators.py
  tests/test_decorators.py
Labels: breaking-change

#2141 Remove unused constants
  ChangeLog
  astroid/__init__.py
  astroid/bases.py
  astroid/brain/brain_ssl.py
  astroid/brain/brain_typing.py
  astroid/brain/brain_unittest.py
  astroid/const.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/rebuilder.py
  tests/test_builder.py
  tests/test_inference.py
  tests/test_nodes.py
  tests/test_nodes_lineno.py
  tests/test_protocols.py
  tests/test_regrtest.py
  tests/test_scoped_nodes.py
  tests/test_utils.py
Labels: breaking-change

#2143 Cleanup rebuilder after dropping py37
  astroid/rebuilder.py
Labels: Maintenance

#2142 Various `TryStar` fixes
  ChangeLog
  astroid/__init__.py
  astroid/node_classes.py
  astroid/nodes/__init__.py
  astroid/nodes/as_string.py
  astroid/nodes/node_ng.py
  astroid/rebuilder.py
  doc/api/astroid.nodes.rst
  tests/test_group_exceptions.py
Labels: Bug 🪳, ast, backport maintenance/2.15.x

#2144 Bump astroid to 2.15.4, update changelog
  ChangeLog
  astroid/__pkginfo__.py
  tbump.toml
Labels: Maintenance

#2145 Merge changes following 2.15.4 release
  ChangeLog
  astroid/__init__.py
  astroid/node_classes.py
  astroid/nodes/__init__.py
  astroid/nodes/as_string.py
  astroid/nodes/node_ng.py
  astroid/rebuilder.py
  doc/api/astroid.nodes.rst
  tests/test_group_exceptions.py
Labels: Maintenance

#2139 Remove ``lazy_object_proxy`` as a dependency
  ChangeLog
  astroid/bases.py
  astroid/util.py
  pyproject.toml
Labels: Maintenance, dependency

#2138 Make all arguments to ``nodes.NodeNG.__init__`` required
  ChangeLog
  astroid/bases.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_fstrings.py
  astroid/brain/brain_random.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  tests/test_object_model.py
  tests/test_transforms.py
Labels: Enhancement ✨

#2150 Fix the signature of ``infer_call_result``
  ChangeLog
  astroid/bases.py
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_functools.py
  astroid/interpreter/objectmodel.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/objects.py
  tests/test_scoped_nodes.py
  tests/test_transforms.py
Labels: Enhancement ✨

#2152 Remove deprecated nodes
  ChangeLog
  astroid/__init__.py
  astroid/node_classes.py
  astroid/nodes/__init__.py
  astroid/nodes/node_classes.py
  doc/api/astroid.nodes.rst
Labels: breaking-change

#2153 Remove deprecated `is_sys_guard` + `is_typing_guard`
  ChangeLog
  astroid/nodes/node_classes.py
  tests/test_nodes.py
Labels: breaking-change

#2157 Yield directly from `_explicit_inference` in `NodeNG.infer()`
  astroid/nodes/node_ng.py
Labels: topic-performance
