Repository pylint-dev/astroid, pull requests merged in 2024-09, with the labels that each got.

#2537 Add ruff exclusions to pyproject.toml
  .pre-commit-config.yaml
  pyproject.toml
Labels: Maintenance

#2539 Fix type annotations for tuple parameters
  astroid/interpreter/_import/spec.py
Labels: Maintenance

#2540 Do not reassign submodule_path parameters in method bodies
  astroid/interpreter/_import/spec.py
Labels: topic-performance, Maintenance

#2542 Move Pylint exclusions to pylintrc
  .pre-commit-config.yaml
  pylintrc
Labels: Maintenance

#2545 Use extend-exclude instead of exclude in ruff config
  pyproject.toml
Labels: Maintenance

#2541 Fix additional mypy errors and expand CI checks to more files
  astroid/_ast.py
  astroid/brain/brain_argparse.py
  astroid/brain/brain_boto3.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_crypt.py
  astroid/brain/brain_ctypes.py
  astroid/brain/brain_curses.py
  astroid/brain/brain_datetime.py
  astroid/brain/brain_dateutil.py
  astroid/brain/brain_functools.py
  astroid/brain/brain_hashlib.py
  astroid/brain/brain_http.py
  astroid/brain/brain_hypothesis.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/brain/brain_numpy_core_fromnumeric.py
  astroid/brain/brain_numpy_core_multiarray.py
  astroid/brain/brain_numpy_core_numeric.py
  astroid/brain/brain_numpy_core_numerictypes.py
  astroid/brain/brain_numpy_core_umath.py
  astroid/brain/brain_numpy_ma.py
  astroid/brain/brain_numpy_random_mtrand.py
  astroid/brain/brain_pathlib.py
  astroid/brain/brain_pkg_resources.py
  astroid/brain/brain_pytest.py
  astroid/brain/brain_qt.py
  astroid/brain/brain_re.py
  astroid/brain/brain_regex.py
  astroid/brain/brain_responses.py
  astroid/brain/brain_scipy_signal.py
  astroid/brain/brain_sqlalchemy.py
  astroid/brain/brain_ssl.py
  astroid/brain/brain_subprocess.py
  astroid/brain/brain_threading.py
  astroid/brain/brain_type.py
  astroid/brain/brain_typing.py
  astroid/brain/brain_unittest.py
  pyproject.toml
Labels: Maintenance

#2561 Remove newstyle variable given old-style class support should be removed
  astroid/helpers.py
  astroid/interpreter/objectmodel.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/objects.py
  tests/test_builder.py
  tests/test_python3.py
  tests/test_scoped_nodes.py
Labels: Maintenance

#2567 Fix inference regression with property setters
  ChangeLog
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/test_inference.py
Labels: Bug 🪳, backport maintenance/3.3.x

#2570 Post 3.3.3
  CONTRIBUTORS.txt
  ChangeLog
  astroid/brain/brain_attrs.py
  script/.contributors_aliases.json
  tests/brain/test_attr.py
Labels: Maintenance

#2572 Fix bug with `manager.clear_cache()` not fully clearing the cache
  ChangeLog
  astroid/manager.py
  tests/test_manager.py
  tests/testdata/python3/data/cache/__init__.py
  tests/testdata/python3/data/cache/a.py
Labels: Bug 🪳, backport maintenance/3.3.x

#2574 Check for empty format specs
  ChangeLog
  astroid/nodes/node_classes.py
  tests/test_inference.py
Labels: Crash 💥, backport maintenance/3.3.x

#2575 Address pylint 3.3 messages
  astroid/bases.py
  astroid/exceptions.py
  astroid/nodes/_base_nodes.py
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/typing.py
  pylintrc
Labels: Maintenance, backport maintenance/3.3.x

#2578 fix issue when inferring single-node or non-const JoinedStr
  ChangeLog
  astroid/nodes/node_classes.py
  tests/test_inference.py
Labels: Bug 🪳, backport maintenance/3.3.x

#2581 Post 3.3.4
  ChangeLog
Labels: Maintenance

#2583 change the type annotation error heuristic
  astroid/builder.py
  tests/test_builder.py
  tests/test_nodes.py
Labels: Bug 🪳, backport maintenance/3.3.x

#2550 Consolidate numpy member transforms to reduce function calls
  astroid/brain/brain_numpy_core_function_base.py
  astroid/brain/brain_numpy_core_multiarray.py
  astroid/brain/brain_numpy_core_numeric.py
  astroid/brain/brain_numpy_utils.py
Labels: topic-performance

#2591 Enable design complexity checks
  astroid/arguments.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_gi.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/decorators.py
  astroid/filter_statements.py
  astroid/nodes/_base_nodes.py
  astroid/nodes/node_ng.py
  astroid/protocols.py
  pylintrc
  tests/test_inference.py
  tests/test_nodes_lineno.py
Labels: Maintenance
