Repository pylint-dev/astroid, pull requests merged in 2024-02, with the labels that each got.

#2369 Remove python 3.7 workaround in test
  tests/test_constraint.py
Labels: Maintenance

#2371 Add members to `ParamSpec` stub
  ChangeLog
  astroid/brain/brain_typing.py
  tests/brain/test_brain.py
Labels: Bug 🪳, backport maintenance/3.0.x

#2358 Fix `UnicodeDecodeError.object` inferred as `str` instead of `bytes`
  ChangeLog
  astroid/interpreter/objectmodel.py
  tests/test_object_model.py
Labels: Bug 🪳, backport maintenance/3.0.x

#2374 Bump astroid to 3.0.3, update changelog
  ChangeLog
  astroid/__pkginfo__.py
  tbump.toml
Labels: Maintenance

#2380 Include modname in AST warnings
  ChangeLog
  astroid/_ast.py
  astroid/builder.py
  tests/test_builder.py
Labels: python 3.12

#2386 Suppress SyntaxWarnings when parsing modules
  ChangeLog
  astroid/builder.py
Labels: ast, python 3.12

#2388 Fix coverage artifact combination step
  .github/workflows/ci.yaml
Labels: Maintenance
