Repository pylint-dev/astroid, pull requests merged in 2024-05, with the labels that each got.

#2422 [sphinx] Fix path to source
  .git-blame-ignore-revs
  doc/conf.py
Labels: Maintenance

#2375 Prefer `.pyi` stubs
  ChangeLog
  astroid/interpreter/_import/spec.py
  astroid/modutils.py
  requirements_full.txt
  tests/brain/test_attr.py
  tests/test_modutils.py
Labels: Enhancement ✨

#2428 Improve performance of _get_zipimporters
  astroid/interpreter/_import/spec.py
Labels: Enhancement ✨

#2432 Fix RecursionError in `infer_call_result()`
  ChangeLog
  astroid/bases.py
  tests/test_inference.py
Labels: pylint-tested, backport maintenance/3.2.x

#2437 Add prefer_stubs configuration
  ChangeLog
  astroid/interpreter/_import/spec.py
  astroid/manager.py
  astroid/modutils.py
  tests/test_modutils.py
Labels: backport maintenance/3.2.x

#2441 Post 3.2.1
  ChangeLog
Labels: Maintenance

#2440 Upgrade pylint in pre-commit config
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  requirements_dev.txt
Labels: Maintenance

#2429 Cache _has_init calls to avoid repeated stats
  astroid/manager.py
  astroid/modutils.py
Labels: topic-performance

#2433 Improve inference for generic classes (PEP 695)
  ChangeLog
  astroid/brain/brain_typing.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/protocols.py
  tests/brain/test_brain.py
  tests/test_protocols.py
Labels: python 3.12, backport maintenance/3.2.x

#2445 Bump astroid to 3.2.2, update changelog
  ChangeLog
  astroid/__pkginfo__.py
  tbump.toml
Labels: Maintenance

#2446 Post 3.2.2
  ChangeLog
Labels: Maintenance

#2443 Drop support for Python 3.8
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  ChangeLog
  astroid/_backport_stdlib_names.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_collections.py
  astroid/brain/brain_dataclasses.py
  astroid/brain/brain_hashlib.py
  astroid/brain/brain_re.py
  astroid/brain/brain_regex.py
  astroid/brain/brain_subprocess.py
  astroid/brain/brain_type.py
  astroid/brain/brain_typing.py
  astroid/const.py
  astroid/context.py
  astroid/modutils.py
  astroid/nodes/_base_nodes.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/raw_building.py
  astroid/rebuilder.py
  astroid/transforms.py
  astroid/typing.py
  pylintrc
  pyproject.toml
  tests/brain/test_brain.py
  tests/brain/test_hashlib.py
  tests/brain/test_regex.py
  tests/brain/test_unittest.py
  tests/test_builder.py
  tests/test_inference.py
  tests/test_lookup.py
  tests/test_nodes.py
  tests/test_nodes_lineno.py
  tests/test_object_model.py
  tests/test_python3.py
  tests/test_scoped_nodes.py
Labels: Maintenance
