Repository pylint-dev/astroid, pull requests merged in 2024-10, with the labels that each got.

#2596 Fix crashes with large positive and negative list multipliers
  ChangeLog
  astroid/protocols.py
  tests/test_protocols.py
Labels: topic-performance, Crash 💥

#2595 Remove unused numpy utility functions
  ChangeLog
  astroid/brain/brain_numpy_utils.py
Labels: breaking-change

#2555 Fix namedtuple parent
  astroid/brain/brain_namedtuple_enum.py
Labels: pylint-tested

#2601 Post 3.3.5
  ChangeLog
Labels: Maintenance

#2536 Clarify on non-Module roots
  astroid/brain/brain_argparse.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/manager.py
  astroid/nodes/node_ng.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/objects.py
  astroid/raw_building.py
  tests/test_nodes.py
Labels: Bug 🪳

#2589 Change order of search path to fix inconsistency between pylint and astroid.
  ChangeLog
  astroid/modutils.py
  astroid/util.py
  tests/test_modutils.py
Labels: Bug 🪳

#2607 Bump CI jobs to python 3.13
  .github/workflows/ci.yaml
  .github/workflows/release.yml
Labels: Maintenance

#2602 make constants have synthetic root as their parent
  ChangeLog
  astroid/brain/brain_argparse.py
  astroid/brain/brain_builtin_inference.py
  astroid/brain/brain_namedtuple_enum.py
  astroid/manager.py
  astroid/nodes/__init__.py
  astroid/nodes/node_classes.py
  astroid/nodes/scoped_nodes/__init__.py
  astroid/nodes/scoped_nodes/scoped_nodes.py
  astroid/objects.py
  tests/test_nodes.py
  tests/test_regrtest.py
Labels: Maintenance
