Repository pylint-dev/astroid, pull requests merged in 2024-12, with the labels that each got.

#2647 Add compatibility with python 3.13.1
  ChangeLog
  astroid/brain/brain_collections.py
  astroid/const.py
Labels: Bug 🪳, backport maintenance/3.3.x

#2652 Post 3.3.6
  ChangeLog
Labels: Maintenance

#2653 Update python versions in tox configuration
  tox.ini
Labels: Maintenance

#2648 Add missing docstring on enum name property
  astroid/brain/brain_namedtuple_enum.py
  tests/brain/test_enum.py
Labels: Needs review 🔍, Needs decision :lock:

#2657 Fix `collections.abc` imports on Python 3.13.0 and 3.13.1
  ChangeLog
  astroid/brain/brain_collections.py
  astroid/const.py
  astroid/interpreter/_import/spec.py
  tests/brain/test_brain.py
Labels: Brain 🧠, High priority, backport maintenance/3.3.x, python 3.13

#2659 Bump astroid to 3.3.7, update changelog
  CONTRIBUTORS.txt
  ChangeLog
  astroid/__pkginfo__.py
  tbump.toml
Labels: Maintenance

#2660 Merge maintenance following 3.3.7 rekease
  CONTRIBUTORS.txt
  ChangeLog
  astroid/interpreter/_import/spec.py
Labels: Maintenance

#2661 Skip flaky recursion test on PyPy
  tests/test_transforms.py
Labels: Maintenance, backport maintenance/3.3.x

#2663 Skip flaky recursion test on PyPy (#2661)
  tests/test_transforms.py
Labels: Maintenance

#2665 Another attempt at fixing the `collections.abc` issue for Python 3.13
  ChangeLog
  astroid/interpreter/_import/spec.py
Labels: backport maintenance/3.3.x

#2667 Post 3.3.8
  ChangeLog
Labels: Maintenance
