Repository pylint-dev/astroid, pull requests merged in 2024-08, with the labels that each got.

#2459 Implement inference for `JoinedStr` and `FormattedValue`
  ChangeLog
  astroid/nodes/node_classes.py
  tests/test_inference.py
Labels: Bug 🪳

#2489 [PY312] Add support for ssl.OP_LEGACY_SERVER_CONNECT
  ChangeLog
  astroid/brain/brain_ssl.py
  tests/brain/test_ssl.py
Labels: python 3.12

#2496 Fix pylint regression with invalid format strings
  ChangeLog
  astroid/nodes/node_classes.py
  tests/test_inference.py
Labels: Crash 💥, backport maintenance/3.3.x

#2499 Post 3.3.1
  ChangeLog
Labels: Maintenance

#2502 Avoid extra isinstance calls in _visit_generic
  astroid/transforms.py
Labels: topic-performance

#2500 Avoid overhead of cast() calls when not type checking
  astroid/transforms.py
Labels: Enhancement ✨, topic-performance

#2503 [PY313] Add stubs for soft-deprecated typing members
  ChangeLog
  astroid/brain/brain_typing.py
Labels: backport maintenance/3.3.x, python 3.13

#2506 Post 3.3.2
  ChangeLog
Labels: Maintenance

#2501 Add cached version of os.path.isfile to avoid repetitive I/O
  astroid/interpreter/_import/spec.py
  astroid/manager.py
  astroid/modutils.py
Labels: topic-performance

#2509 Make Finder.find_module static to facilitate future caching
  astroid/interpreter/_import/spec.py
Labels: topic-performance

#2507 Remove unnecessary isinstance calls from transform predicates
  astroid/brain/brain_numpy_ndarray.py
  astroid/brain/brain_type.py
  astroid/brain/brain_typing.py
Labels: topic-performance

#2529 Use a tuple for processed parameter to facilitate future caching
  astroid/interpreter/_import/spec.py
Labels: Maintenance

#2532 fix the documentation and the error message of modpath_from_file
  astroid/modutils.py
Labels: Documentation :green_book:
