Repository pylint-dev/astroid, pull requests merged in 2024-07, with the labels that each got.

#2455 Make the "test_helpers.py" test file runnable by itself
  tests/test_helpers.py
Labels: Maintenance

#2458 Fix AssertionError when inferring a property consisting of a partial function
  ChangeLog
  astroid/nodes/scoped_nodes/scoped_nodes.py
  tests/test_regrtest.py
Labels: Crash 💥, backport maintenance/3.2.x

#2468 Avoid reporting unary/binary op type errors for ambiguous inference
  ChangeLog
  astroid/nodes/node_classes.py
  tests/test_inference.py
Labels: backport maintenance/3.2.x

#2477 Post 3.2.4
  ChangeLog
Labels: Maintenance

#2482 Skip test_numpy_distutils on 3.12+
  tests/test_regrtest.py
Labels: Maintenance

#2484 Remove f-strings brain
  astroid/brain/brain_fstrings.py
  astroid/brain/helpers.py
  tests/brain/test_brain.py
Labels: topic-performance, pylint-tested, Maintenance

#2485 Qualify setuptools requirement to Python >=3.12
  requirements_full.txt
Labels: Maintenance

#2486 Improve class util typing
  astroid/nodes/scoped_nodes/scoped_nodes.py
Labels: Maintenance

#2487 Skip `test_no_user_warning()` without pip
  tests/test_manager.py
Labels: Maintenance
