Repository pylint-dev/astroid, pull requests merged in 2025-08, with the labels that each got.

#2793 Add basic support for TemplateStr
  ChangeLog
  astroid/__init__.py
  astroid/nodes/__init__.py
  astroid/nodes/as_string.py
  astroid/nodes/node_classes.py
  astroid/rebuilder.py
  tests/test_nodes.py
Labels: Enhancement ✨, ast, python 3.14

#2795 Export ForwardRef from typing in 3.14
  astroid/brain/brain_typing.py
Labels: Brain 🧠, python 3.14

#2796 [fix] Fix crash when comparing invalid dict literal
  ChangeLog
  astroid/nodes/node_classes.py
  tests/test_regrtest.py
Labels: Crash 💥

#2804 Add workflow_dispatch trigger [ci]
  .github/workflows/ci.yaml
Labels: Maintenance

#2809 [fix] Fix parsing deeply nested parentheses causes MemoryError
  ChangeLog
  astroid/builder.py
  tests/test_regrtest.py
Labels: Crash 💥
