Repository pylint-dev/astroid, pull requests merged in 2025-03, with the labels that each got.

#2690 [Backport maintenance/3.3.x] Fix missing __dict__ (#2685)
  astroid/raw_building.py
  requirements_dev.txt
  requirements_minimal.txt
  tests/test_raw_building.py
Labels: Bug 🪳

#2696 Update release workflow to use Trusted Publishing
  .github/workflows/release.yml
  ChangeLog
Labels: Maintenance, backport maintenance/3.3.x

#2699 Merge maintenance in main following 3.3.9 release
  .pre-commit-config.yaml
  ChangeLog
  script/.contributors_aliases.json
Labels: Maintenance

#2698 Minor improvements to release workflow
  .github/workflows/release.yml
Labels: Maintenance, backport maintenance/3.3.x

#2700 Add additional permissions for backport workflow
  .github/workflows/backport.yml
Labels: Maintenance, backport maintenance/3.3.x

#2702 Avoid importing submodules sharing names with standard library modules
  ChangeLog
  astroid/interpreter/_import/spec.py
  tests/test_modutils.py
  tests/testdata/python3/data/divide_by_zero.py
Labels: Bug 🪳, backport maintenance/3.3.x

#2705 Cache _is_setuptools_namespace results to avoid repetitive I/O
  astroid/interpreter/_import/spec.py
  astroid/manager.py
Labels: topic-performance

#2715 [setuptools] Force the upgrade of setuptools > 77
  pyproject.toml
Labels: Maintenance, backport maintenance/3.3.x
