Repository pylint-dev/astroid, pull requests merged in 2025-09, with the labels that each got.

#2815 [Backport maintenance/3.3.x] Partial backport of (#2765)
  requirements_full.txt
  tests/test_manager.py
Labels: Maintenance

#2816 [ci] Use setup-python output for pypy cache key
  .github/workflows/ci.yaml
Labels: Maintenance

#2824 Use yaml anchors for workflow
  .github/workflows/ci.yaml
Labels: Maintenance

#2823 Support boolean truthiness constraints in inference
  ChangeLog
  astroid/constraint.py
  tests/test_constraint.py
  tests/test_inference.py
Labels: Enhancement ✨, inference

#2827 Revert the botched bump to 4.0.0b4-dev0
  astroid/__pkginfo__.py
  tbump.toml
Labels: Maintenance

#2835 Use match for statistics brain
  astroid/brain/brain_statistics.py
Labels: Maintenance

#2836 Extend constraints to support ternary expressions
  ChangeLog
  astroid/constraint.py
  astroid/context.py
  tests/test_constraint.py
Labels: inference

#2837 Deprecate nodes import from astroid
  ChangeLog
  astroid/__init__.py
  tests/test_nodes.py
Labels: deprecation

#2840 fix: add missing http status codes
  astroid/brain/brain_http.py
Labels: Brain 🧠
