Repository pylint-dev/astroid, pull requests merged in 2025-05, with the labels that each got.

#2722 Pick correct file if two files with the same name but with different extensions exist
  ChangeLog
  astroid/modutils.py
  script/.contributors_aliases.json
  tests/test_modutils.py
  tests/testdata/python3/pyi_data/find_test/__init__.weird_ext
  tests/testdata/python3/pyi_data/find_test/standalone_file.weird_ext
Labels: Bug 🪳, backport maintenance/3.3.x

#2728 Pick correct file if two files with the same name but with different extensions exist
  ChangeLog
  astroid/modutils.py
  script/.contributors_aliases.json
  tests/test_modutils.py
  tests/testdata/python3/pyi_data/find_test/__init__.weird_ext
  tests/testdata/python3/pyi_data/find_test/standalone_file.weird_ext
Labels: Bug 🪳

#2730 Bump astroid to 3.3.10, update changelog
  ChangeLog
  astroid/__pkginfo__.py
  script/.contributors_aliases.json
  tbump.toml
Labels: Maintenance

#2732 Merge maintenance into main following 3.3.10 release
  .pre-commit-config.yaml
  CONTRIBUTORS.txt
  ChangeLog
  script/.contributors_aliases.json
Labels: Maintenance

#2736 [fix] Crash when parsing an empty arbitrary expression with ``extract_node``
  ChangeLog
  astroid/builder.py
  tests/test_regrtest.py
Labels: Crash 💥, backport maintenance/3.3.x

#2738 [fix] Prevent crash on slice decorator for ``six`` decorated function
  ChangeLog
  astroid/brain/brain_six.py
  tests/test_regrtest.py
Labels: Crash 💥, backport maintenance/3.3.x

#2739 [fix] Fix a crash when the root of a node is not a module but is unknown
  ChangeLog
  astroid/nodes/node_ng.py
  tests/test_regrtest.py
Labels: Crash 💥, backport maintenance/3.3.x

#2744 Fix another non module root
  astroid/interpreter/objectmodel.py
  astroid/nodes/node_classes.py
  astroid/nodes/node_ng.py
  astroid/protocols.py
  tests/test_helpers.py
  tests/test_nodes.py
  tests/test_regrtest.py
Labels: Bug 🪳, backport maintenance/3.3.x

#2745 [tests] Simplify _locals test so it's easier to see what's wrong
  tests/test_builder.py
Labels: Maintenance

#2747 Initial fixes for Python 3.14
  astroid/brain/brain_pathlib.py
  astroid/brain/brain_typing.py
  astroid/const.py
  tests/brain/test_brain.py
  tests/brain/test_pathlib.py
  tests/test_inference.py
Labels: Maintenance, python 3.14

#2748 [Backport maintenance/3.3.x] Initial fixes for Python 3.14 (#2747)
  astroid/brain/brain_pathlib.py
  astroid/brain/brain_typing.py
  astroid/const.py
  tests/brain/test_brain.py
  tests/brain/test_pathlib.py
  tests/test_inference.py
Labels: Maintenance, python 3.14

#2749 Improve backport job permissions
  .github/workflows/backport.yml
Labels: Maintenance, backport maintenance/3.3.x

#2751 Use custom Github App to authenticate backport job
  .github/workflows/backport.yml
Labels: Maintenance, backport maintenance/3.3.x

#2735 Include subclasses of standard property classes as property decorators
  ChangeLog
  astroid/bases.py
  tests/test_nodes.py
Labels: Bug 🪳, backport maintenance/3.3.x
